"""Single `kosha` entry point with subcommands for shell-based harnesses.
Default output is readable markdown; pass `--as-json` for JSON (piping/harnesses)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cli.ipynb.

# %% auto #0
__all__ = ['CMDS', 'sync', 'context', 'repo_context', 'env_context', 'ni', 'watch', 'public_api', 'api_paths', 'dep_stack',
           'top_nodes', 'daemon', 'diff', 'find_similar_cli', 'surprising', 'main']

# %% ../nbs/03_cli.ipynb #cell-imports
import json, sys
from fastcore.script import call_parse, Param
from .core import Kosha, env_pkg_versions

# %% ../nbs/03_cli.ipynb #cell-helpers
def _to_json(obj):
    'Recursively convert kosha result objects to JSON-serializable types.'
    if isinstance(obj, (set, frozenset)): return sorted(obj)
    if isinstance(obj, dict): return {k: _to_json(v) for k, v in obj.items()}
    if hasattr(obj, '__iter__') and not isinstance(obj, str): return [_to_json(x) for x in obj]
    return obj

def _print_results(results):
    'Print context/search results as readable markdown blocks.'
    for r in results:
        m = r.get('metadata', {}) if isinstance(r, dict) else {}
        mod = m.get('mod_name', r.get('path', 'unknown')) if m else r.get('path', 'unknown')
        line = m.get('lineno', '?') if m else '?'
        pr = r.get('pagerank', 0) or 0
        print(f"\n## {mod}  (line {line})  [pagerank: {pr:.5f}]")
        content = (r.get('content', '') or '')[:300]
        if content: print(f"```\n{content}\n```")
        callers = r.get('callers', [])
        if callers: print(f"Callers: {', '.join(list(callers)[:5])}")

# %% ../nbs/03_cli.ipynb #cell-sync
@call_parse
def sync(
    pkgs:str=None,       # comma-separated package names; defaults to all pyproject.toml deps
    parallel:bool=False, # run repo, env, and graph sync in parallel
    embed:bool=True,     # embed code chunks (set False for fast metadata-only update)
):
    'Sync repo + env packages + call graph into .kosha/ databases.'
    k = Kosha()
    pkg_list = pkgs.split(',') if pkgs else None
    k.sync(pkgs=pkg_list, in_parallel=parallel, embed=embed)

# %% ../nbs/03_cli.ipynb #cell-context
@call_parse
def context(
    query:str,           # search query (supports key:value filters e.g. package:fastcore)
    limit:int=10,        # max results
    repo:bool=True,      # include repo results
    env:bool=True,       # include env results
    graph:bool=True,     # include call graph enrichment
    as_json:bool=False,  # output JSON instead of markdown
):
    'Fan-out semantic search over repo and env, optionally graph-enriched.'
    k = Kosha()
    results = k.context(query, limit=limit, repo=repo, env=env, graph=graph)
    if as_json: print(json.dumps(_to_json(results)))
    else: _print_results(results)

# %% ../nbs/03_cli.ipynb #cell-repo-context
@call_parse
def repo_context(
    query:str,          # search query
    limit:int=10,       # max results
    as_json:bool=False, # output JSON
):
    'Semantic + keyword search over indexed repo code only.'
    k = Kosha()
    results = k.repo_context(query, limit=limit)
    if as_json: print(json.dumps(_to_json(results)))
    else: _print_results(results)

# %% ../nbs/03_cli.ipynb #cell-env-context
@call_parse
def env_context(
    query:str,          # search query (package names auto-detected as filters)
    limit:int=10,       # max results
    as_json:bool=False, # output JSON
):
    'Semantic search over indexed env packages only.'
    k = Kosha()
    results = k.env_context(query, limit=limit)
    if as_json: print(json.dumps(_to_json(results)))
    else: _print_results(results)

# %% ../nbs/03_cli.ipynb #cell-ni
@call_parse
def ni(
    mod_name:str,       # fully-qualified module node name e.g. fastcore.basics.merge
    as_json:bool=False, # output JSON
):
    'Node info: callers, callees, co_dispatched, pagerank for a single graph node.'
    k = Kosha()
    result = k.ni(mod_name)
    if as_json: print(json.dumps(_to_json(result)))
    else:
        print(f"\n## {mod_name}")
        print(f"pagerank: {result.get('pagerank', 0):.5f}")
        callers = result.get('callers', [])
        callees = result.get('callees', [])
        co = result.get('co_dispatched', [])
        if callers: print(f"Callers ({len(callers)}): {', '.join(list(callers)[:10])}")
        if callees: print(f"Callees ({len(callees)}): {', '.join(list(callees)[:10])}")
        if co: print(f"Co-dispatched: {', '.join(list(co)[:10])}")

# %% ../nbs/03_cli.ipynb #cell-watch
@call_parse
def watch(
    dir:str=None,  # directory to watch; defaults to repo root
):
    "Live incremental re-index on file changes. Blocking \u2014 Ctrl-C to stop."
    from pathlib import Path as _Path
    k = Kosha()
    k.watch_repo(dir=_Path(dir) if dir else None)

# %% ../nbs/03_cli.ipynb #cell-public-api
@call_parse
def public_api(
    pkg:str,            # package name e.g. "fastcore" or submodule "fastcore.basics"
    module:str=None,    # restrict to a submodule (overrides pkg for scoping)
    as_json:bool=False, # output JSON
):
    "List public API entries for a package (respects __all__ + @patch methods)."
    k = Kosha()
    target = module or pkg
    results = k.public_api(target)
    if as_json: print(json.dumps(_to_json(results)))
    else:
        print(f"\n## Public API: {target}  ({len(results)} entries)")
        for r in results:
            name = r.get('mod_name', '')
            doc = r.get('docstring', '') or ''
            suffix = f'  # {doc.splitlines()[0][:60]}' if doc.strip() else ''
            print(f"  {name}{suffix}")

# %% ../nbs/03_cli.ipynb #cell-api-paths
@call_parse
def api_paths(
    from_pkg:str,       # source package (call origin)
    to_pkg:str,         # target package (call destination)
    k:int=15,           # top-k API nodes per package to consider
    as_json:bool=False, # output JSON
):
    "Shortest call-graph paths from from_pkg public API to to_pkg public API."
    ko = Kosha()
    paths = ko.api_call_paths(from_pkg, to_pkg, k=k)
    if as_json: print(json.dumps(_to_json(paths)))
    else:
        print(f"\n## Call paths: {from_pkg} \u2192 {to_pkg}  ({len(paths)} targets reached)")
        for target, path in sorted(paths.items(), key=lambda x: len(x[1])):
            print(f"\n  \u2192 {target}  (hops: {len(path)})")
            _arr = ' → '
        print(f"    {_arr.join(path)}")

# %% ../nbs/03_cli.ipynb #cell-dep-stack
@call_parse
def dep_stack(
    seeds:str=None,     # comma-separated seed package names; defaults to pyproject.toml deps
    depth:int=1,        # BFS depth
    as_json:bool=False, # output JSON
):
    "BFS dependency layers from seed packages, ordered by coupling strength."
    k = Kosha()
    seed_list = seeds.split(',') if seeds else list(env_pkg_versions().keys())
    layers = k.dep_stack(seeds=seed_list, depth=depth)
    if as_json: print(json.dumps(_to_json(layers)))
    else:
        for i, layer in enumerate(layers):
            label = "seeds" if i == 0 else f"depth {i}"
            pkgs = sorted(layer) if isinstance(layer, (set, frozenset)) else layer
            print(f"\n## Layer {i} ({label}): {', '.join(pkgs)}")

# %% ../nbs/03_cli.ipynb #cell-top-nodes
@call_parse
def top_nodes(
    pkg:str,            # package name e.g. "fastcore"
    k:int=5,            # number of top nodes to return
    as_json:bool=False, # output JSON
):
    "Top-k public API nodes for a package ranked by PageRank in the call graph."
    ko = Kosha()
    nodes = ko.top_nodes(pkg, k=k)
    if as_json: print(json.dumps(_to_json(nodes)))
    else:
        print(f"\n## Top {k} nodes: {pkg}")
        for node in nodes: print(f"  {node}")

# %% ../nbs/03_cli.ipynb #cell-daemon
_DISPATCH = {
    'context':        lambda k, a: k.context(**a),
    'repo_context':   lambda k, a: k.repo_context(**a),
    'env_context':    lambda k, a: k.env_context(**a),
    'ni':             lambda k, a: k.ni(a['mod_name']),
    'graph_diff':     lambda k, a: k.graph_diff(),
    'find_similar':   lambda k, a: k.find_similar(**a),
    'surprising':     lambda k, a: k.surprising_connections(**a),
    'top_nodes':      lambda k, a: k.top_nodes(**a),
    'public_api':     lambda k, a: k.public_api(**a),
    'api_call_paths': lambda k, a: k.api_call_paths(**a),
    'sync':           lambda k, a: (k.sync(**a), 'synced')[1],
}

@call_parse
def daemon():
    "Persistent kosha kernel. Reads newline-delimited JSON from stdin, writes results to stdout."
    k = Kosha()
    print(json.dumps({"ok": True, "status": "ready"}), flush=True)
    for line in sys.stdin:
        if not (line := line.strip()): continue
        try:
            req = json.loads(line)
            fn = _DISPATCH[req['cmd']]
            print(json.dumps({"ok": True, "result": _to_json(fn(k, req.get('args', {})))}), flush=True)
        except Exception as e:
            print(json.dumps({"ok": False, "error": str(e)}), flush=True)


# %% ../nbs/03_cli.ipynb #cell-diff
@call_parse
def diff(as_json:bool=False):
    "Show delta between current graph and last snapshot (run after kosha sync)."
    k = Kosha()
    d = k.graph_diff()
    if as_json: print(json.dumps(_to_json(d)))
    else:
        print(f"New nodes ({len(d['new_nodes'])}): {', '.join(d['new_nodes'][:10])}")
        print(f"Removed  ({len(d['removed_nodes'])}): {', '.join(d['removed_nodes'][:10])}")
        print(f"New edges: {len(d['new_edges'])}  Removed edges: {len(d['removed_edges'])}")
        _arr = ' → '
        for node, old, new in d['pagerank_shifts'][:5]:
            print(f"  PageRank shift: {node}  {old:.5f}{_arr}{new:.5f}")


# %% ../nbs/03_cli.ipynb #cell-find-similar
@call_parse
def find_similar_cli(
    node:str,           # fully-qualified node e.g. fastcore.basics.merge
    k:int=10,           # number of similar nodes
    as_json:bool=False, # output JSON
):
    "Find k most embedding-similar nodes (semantic peers, not call-graph neighbors)."
    ko = Kosha()
    results = ko.find_similar(node, k=k)
    if as_json: print(json.dumps(_to_json(results)))
    else: _print_results(results)


# %% ../nbs/03_cli.ipynb #cell-surprising
@call_parse
def surprising(
    top_n:int=10,             # number of surprising connections to show
    no_embeddings:bool=False, # skip embedding distance scoring (faster)
    as_json:bool=False,       # output JSON
):
    "Show top surprising cross-module call relationships by structural + semantic surprise score."
    k = Kosha()
    results = k.surprising_connections(top_n=top_n, use_embeddings=not no_embeddings)
    if as_json: print(json.dumps(_to_json(results)))
    else:
        _arr = ' → '
        for s in results:
            emb = f" emb_dist={s['embedding_distance']}" if s.get('embedding_distance') is not None else ''
            print(f"{s['caller']}{_arr}{s['callee']}  kind={s['kind']} surprise={s['surprise_score']}{emb}")


# %% ../nbs/03_cli.ipynb #cell-cmds
CMDS = {
    'sync':           sync,
    'context':        context,
    'repo-context':   repo_context,
    'env-context':    env_context,
    'ni':             ni,
    'watch':          watch,
    'public-api':     public_api,
    'api-paths':      api_paths,
    'dep-stack':      dep_stack,
    'top-nodes':      top_nodes,
    'daemon':         daemon,
    'diff':           diff,
    'find-similar':   find_similar_cli,
    'surprising':     surprising,
}

def main():
    "Entry point for the `kosha` CLI command."
    if len(sys.argv) < 2 or sys.argv[1] not in CMDS:
        cmds = ' | '.join(CMDS)
        print(f"Usage: kosha [{cmds}]")
        sys.exit(0 if len(sys.argv) < 2 else 1)
    cmd = sys.argv.pop(1)
    CMDS[cmd]()

