"""Kosha is a tool for building a context for code generation based on your repo and environment.
It uses a vector database to store code snippets and their embeddings, allowing you to search for relevant code based
on natural language queries.
The core functionality includes managing the database, updating package metadata, embedding code snippets,
and performing context-aware searches."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cr_instr', 'model', 'strict_skip_folder_re', 'strict_skip_file_re', 'emb_doc', 'emb_query', 'parse', 'repo_root',
           'mv_skill_md', 'arun', 'pkg_trans_deps', 'env_pkg_versions', 'embedder', 'static_embedder', 'Kosha',
           'pkg_doc', 'has_init', 'embed_chunk', 'process_content', 'count_imp', 'parseq', 'filt2wh']

# %% ../nbs/00_core.ipynb #69029d72f94a2fdc
import ast, os, re
from collections import defaultdict, Counter
from hashlib import md5
from importlib.metadata import version as v, metadata as meta, distribution as dist
from chonkie import AutoEmbeddings
from fastcore.all import (Path, first, patch, timed_cache, L, chunked, parallel, merge, AttrDict,
                          filter_keys, not_, in_, listify, true, fdelegates)
from fastcore.xdg import xdg_data_home
from tqdm import tqdm
from functools import lru_cache
from json import loads as jl
from litesearch import *

# %% ../nbs/00_core.ipynb #bfe18701edf5102
@timed_cache(maxsize=512)
def parse(code=None, p=None):
    "Parse source, tag parents, return (tree, imp, top_fns, all_fns). Cached — called freely."
    if not code and not p: return None, {}, set(), set()
    try: tree = ast.parse(Path(p).read_text(errors='replace') if not code else code)
    except SyntaxError: return None, {}, set(), set()
    [setattr(c,'parent',n) for n in ast.walk(tree) for c in ast.iter_child_nodes(n)]
    is_top = lambda n: isinstance(getattr(n,'parent',None), ast.Module)
    is_fn  = lambda n: isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef,ast.ClassDef))
    is_nm  = lambda n: isinstance(n, ast.Name)
    imp = {}
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            for a in n.names: imp[a.asname or a.name.split('.')[0]] = a.name.split('.')[0]
        elif isinstance(n, ast.ImportFrom):
            pkg = (n.module or '').split('.')[0]
            for a in n.names:
                if a.name != '*': imp[a.asname or a.name] = pkg
                else: imp.setdefault(f'*{pkg}', pkg)
    top = {n.name for n in ast.walk(tree) if is_fn(n) and is_top(n)}
    ca  = {nm for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.value,ast.Call)
           for t in n.targets
           for nm in ([t.id] if is_nm(t) else [e.id for e in t.elts if is_nm(e)] if isinstance(t,ast.Tuple) else [])}
    return tree, imp, top, top | ca

# %% ../nbs/00_core.ipynb #d4532509b3f08ee1
def repo_root() -> Path:
	'Find the root of the current git repository, or None if not in a repo.'
	return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None) -> None:
	"Copy bundled SKILL.md to `.agents/skills/kosha/` at project root or specified dir."
	if not (r := dir or repo_root()): return
	base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
	if not (src := base.joinpath('SKILL.md')).exists(): return
	dest = Path(r).joinpath('.agents', 'skills', 'kosha', 'SKILL.md')
	if dry_run: print(f'Would copy {src} to {dest}')
	else: dest.mk_write(src.read_text(encoding='utf-8'))

# %% ../nbs/00_core.ipynb #8b67e1dd013da45b
def arun(coro) -> any:
	'Run an async coroutine from sync code, even if already inside an event loop'
	import asyncio
	try: asyncio.get_running_loop()
	except RuntimeError: return asyncio.run(coro)
	import concurrent.futures
	with concurrent.futures.ThreadPoolExecutor() as pool: return pool.submit(asyncio.run, coro).result()

# %% ../nbs/00_core.ipynb #82af952c
_req_nm = re.compile(r'^[\w][\w.-]*')

def pkg_trans_deps(seeds:list, depth:int=2) -> L:
	'BFS over importlib.metadata requires: return seeds + all transitive deps up to depth levels (installed only, no optional extras).'
	seen, frontier = set(seeds), set(seeds)
	for _ in range(depth):
		nxt = set()
		for pkg in frontier:
			try:
				for req in (dist(pkg).requires or []):
					if 'extra ==' in req: continue
					if (m := _req_nm.match(req)) and spec(m.group(0)): nxt.add(m.group(0))
			except Exception: pass
		nxt -= seen
		if not nxt: break
		seen |= nxt; frontier = nxt
	return L(seen)

# %% ../nbs/00_core.ipynb #c475a3af79bdd694
@lru_cache(maxsize=1)
def env_pkg_versions(pyproject=True, depth:int=1) -> dict:
	'''Get a dict of installed package versions using importlib.metadata.
	passing depth traverse multiple layers of dependencies'''
	pkgs = installed_packages(pyproject=pyproject)
	if pyproject and depth: pkgs = pkg_trans_deps(pkgs, depth)
	return merge(*pkgs.map(lambda p: {dist(p).metadata['Name']: dist(p).version}))

# %% ../nbs/00_core.ipynb #3ccb8e947caec348
cr_instr = AttrDict(query="Represent this query for searching relevant code: {text}", document="{text}")
model = AttrDict(model='mrsladoje/CodeRankEmbed-onnx-int8', onnx_path='onnx/model.onnx', prompt=cr_instr)
strict_skip_folder_re = r'^[._]|^(?:tests?|examples?|docs?|build|dist)$'
strict_skip_file_re = r'^[._]|^(?:setup\.py|conftest\.py)$'

@timed_cache(3600*24)
def embedder(emb_model=model): return FastEncode(emb_model, parallel=True, batch_size=64)
@timed_cache(3600*24)
def static_embedder(emb_model='minishlab/potion-retrieval-32M'): return AutoEmbeddings().get_embeddings(emb_model)
emb_doc = lambda e:lambda t:e().encode_document(t) if isinstance(e(),FastEncode) else e().embed_batch(listify(t))
emb_query = lambda e:lambda t:e().encode_query(t) if isinstance(e(),FastEncode) else e().embed_batch(listify(t))

# %% ../nbs/00_core.ipynb #8511999ac2824a0b
class Kosha:
	'Kosha allows you to build a context for code generation based on your repo and environment.'
	def __init__(self, dir: Path = None, install_skill: bool = False, xdg_dir: Path = None):
		self.root, self.xdg = Path(dir or repo_root() or '.'), xdg_dir or xdg_data_home()
		if install_skill: mv_skill_md(dir=self.root, dry_run=False)
		self.cp, self.ce = self.root.joinpath('.kosha','code.db'), self.xdg.joinpath('kosha','env.db')
		for p in (self.cp, self.ce): p.parent.mkdir(parents=True, exist_ok=True)
		self.codedb, self.envdb = database(self.cp), database(self.ce)
		self.code_st,self.env_st = self.codedb.get_store(path=str,hash=True),self.envdb.get_store(package=str,hash=True)
		self.pkg_st, self.pkgs = self.envdb.get_store('pkg_store', hash=True), self.envdb.t.packages
		self.env_pd, self.code_rd = self.envdb.t.pkg_deps, self.codedb.t.repo_deps
		self.pkgs.create(name=str, version=str, summary=str, uploaded_at=float, pk=['name','version'],
			 defaults=dict(uploaded_at='CURRENT_TIMESTAMP'), if_not_exists=True)
		self.env_pd.create(from_pkg=str, to_pkg=str, n_modules=int, if_not_exists=True, pk=['from_pkg','to_pkg'])
		self.code_rd.create(from_module=str, to_pkg=str, n_files=int, if_not_exists=True, pk=['from_module','to_pkg'])

# %% ../nbs/00_core.ipynb #pkg_store_helpers_a1b2
def pkg_doc(pkg) -> dict:
	'Build pkg_store content dict: content=summary+readme, metadata=json.'
	m = meta(pkg)
	_get, _req_re, fn = lambda k: m.get(k,''), re.compile(r'^[\w-]+'), lambda rm: rm.group(0).lower().replace('-','_')
	reqs = ' '.join({fn(rm) for r in (m.get_all('Requires-Dist') or []) if (rm:=_req_re.match(r))})
	summary = _get('Summary')
	cont = summary+'\n'+(m.get_payload() or _get('Description') or '')[:2000].strip()
	return dict(content=cont,
	            metadata=dict(name=pkg, version=v(pkg), keywords=_get('Keywords'), requires=reqs, summary=summary))

# %% ../nbs/00_core.ipynb #5e6e5dace1c5fe8d
def has_init(d: Path) -> bool:
	'True if dir is a Python package root: has __init__.py or a C-extension __init__*.so.'
	return (d / '__init__.py').exists() or bool(list(d.glob('__init__*.so')))

# %% ../nbs/00_core.ipynb #cd93d2c15ca33a8d
os.environ['TOKENIZERS_PARALLELISM']='false'  # to suppress warnings from tokenizers
@patch
def nuke(self:Kosha):
	'Reset the databases by dropping all tables.'
	for p in (self.cp, self.ce): p.parent.delete()

@patch
def _is_pkg_ingested(self:Kosha, pkg:str) -> bool:
	'Check if a package is already ingested and up-to-date.'
	return self.pkgs(select='name, version', where=f'name={pkg!r} and version={v(pkg)!r}')

def embed_chunk(chunk:list,emb_fn=emb_doc, efn=embedder):
	'Embed a list of code chunks using emb_f'
	if not (chunk): return
	c = [b['content'] for b in chunk if b['content'] and b['content'].strip()]
	if not c: return
	for e,b in zip(emb_fn(efn)(c),chunk): b['embedding'] = e.tobytes()
	return chunk

def process_content(store, content:L, embed:bool=True, efn=embedder, sz:int=500):
	'Embed chunks and upsert into store; no-op if content is empty.'
	if not content: return
	if embed: content = parallel(embed_chunk, L(chunked(content, sz)), efn=efn, progress=True, threadpool=True).concat()
	return store.insert_all(content, upsert=True, hash_id='id')

@patch
@fdelegates(process_content)
def process_env(self:Kosha, content=None, reembed=False, **kwargs):
	'Embed all documents in the env store, or only those without embeddings if reembed=False.'
	content = content or self.env_st(where=f'embedding is NULL' if not reembed else None)
	return process_content(self.env_st, content, **kwargs)

def _slug(s): return md5(s.encode('utf-8')).hexdigest() if s else None

def _content(store, where:str=None, f=None):
	'Helper to retrieve content from a store with optional filtering and transformation.'
	c=L(store(select='content', where=where)).filter(lambda c: c['content'] and c['content'].strip()).attrgot('content')
	return c if not f else L(c).map(f)

def count_imp(files, own:str='') -> Counter:
	'External top-level imports from a source-string iterable. Reuses cached _parse.'
	c, fn = Counter(), lambda p: p and p!=own and p[0]!='_'
	def do(f): c.update(set(L(parse(p=f)[1].values()).filter(fn)))
	L(files).map(do)
	return c

@patch
@fdelegates(pkg2chunks)
def update_pkg(self:Kosha, pkg:str, embed=True, exts=code_exts, efn=embedder, verbose=True, **kwargs):
	'Update package metadata in the packages table.'
	assert (o:= spec(pkg)), f'pkg {pkg} is not in environment'
	if verbose: print(f'updating pkg: {pkg} ...')
	ep = self._is_pkg_ingested(pkg)
	if ep and len(self.env_st(where=f'package={pkg!r}')) > 0: return print(f'package {ep} already loaded.') if verbose else None
	pkg_par = Path(o.origin).parent.parent
	mod_fn = lambda p, n: '.'.join(list(Path(p).relative_to(pkg_par).with_suffix('').parts)+[n])
	_get = lambda o,k1,k2: o.get(k1,{}).get(k2,'')
	meta_fn = lambda d: d['metadata'] | dict(mod_name=mod_fn(_get(d,'metadata','path'),_get(d,'metadata','name')))
	fn = lambda d: dict(package=pkg, uploaded_at=_get(d,'metadata','uploaded_at'), metadata=meta_fn(d))
	content, doc = pkg2chunks(pkg, exts=exts, **kwargs).map(lambda d: d | fn(d)), pkg_doc(pkg)
	ex, cont_hash = _content(self.env_st, where=f'package={pkg!r}', f=_slug), {_slug(d['content']): d for d in content}
	if del_ids:=set(ex).difference(cont_hash.keys()): self.env_st.delete_where(where='id in ("%s")'%'","'.join(del_ids))
	ch = filter_keys(cont_hash, not_(in_(ex))).values()
	if ch and self.process_env(ch, embed=embed, efn=efn):
		process_content(self.pkg_st, L(doc), embed=embed, efn=efn)
		counts = count_imp(pkg2files(pkg, exts=['.py']),pkg.replace('-','_').split('.')[0])
		rows = [dict(from_pkg=pkg, to_pkg=dep, n_modules=n) for dep,n in counts.items() if spec(dep)]
		if rows: self.envdb.t.pkg_deps.insert_all(rows, replace=True)
	if verbose: print(f'updated pkg: {pkg} with {len(ch)} new/changed chunks, {len(ex)-len(ch)} unchanged, '
		      f'{len(ex)-len(cont_hash)} removed')
	return self.pkgs.insert(dict(name=pkg, version=v(pkg), summary=_get(doc,'metadata','summary')), ignore=True)

@patch
def rm_pkg(self:Kosha, pkg:str, ver:str=None):
	'Remove a package and its code snippets from the database.'
	wh = f'package={pkg!r} AND version={ver!r}' if ver else f'package={pkg!r}'
	for t in [self.env_st, self.pkgs]: t.delete(where=wh)
	self.pkg_st.delete_where(where=f"json_extract(metadata,'$.name')={pkg!r}")
	self.env_pd.delete_where(where=f'from_pkg={pkg!r}')
	self.pkgs.delete_where(where=f'name={pkg!r}')

@patch
def process_repo(self:Kosha, content=None, reembed=False, **kwargs):
	'Embed all documents in the code store, or only those without embeddings if reembed=False.'
	content = content or self.code_st(where=f'embedding is NULL' if not reembed else None)
	return process_content(self.code_st, content, **kwargs)

@patch
def update_pkgs(self:Kosha, pkgs:str|list=None, embed=True, exts=code_exts, efn=embedder, verbose=True, **kwargs):
	pkgs = set(pkgs).intersection(env_pkg_versions(pyproject=False)) if pkgs else set(env_pkg_versions())
	if verbose: print(f'loading pkgs {pkgs} ......')
	kw = dict(embed=embed, exts=exts, efn=efn, verbose=verbose, **kwargs)
	for pkg in tqdm(pkgs, desc='Updating packages', unit='pkg'): self.update_pkg(pkg, **kw)

@patch
@fdelegates(dir2files)
def update_repo(self:Kosha,
				dir:Path=None,    # directory to index; defaults to repo root
				embed:bool=True,  # embed chunks after parsing
				files:L=None,     # specific paths to (re)index; None = full sync
                exts:str=code_exts,
                efn=embedder,       # embedding function to use for code snippets
                verbose=True, # verbose
				**kwargs              # extra args forwarded to dir2files
				):
	'Index or update repo code chunks. Pass files= for incremental update (e.g. from watcher).'
	dir = Path(dir or self.root)
	if files is None:
		known = {r['path']: r['uploaded_at'] for r in self.code_st(select='path, uploaded_at') if r['path']}
		all_files = dir2files(str(dir), strict_skip_file_re, strict_skip_folder_re,exts=exts, **kwargs)
		to_remove = L(known.keys()).filter(lambda k: k not in all_files.map(str)).concat()
		ch = L(all_files).filter(lambda f: str(f) not in known or known[str(f)] != f.stat().st_mtime)
	else: ch,to_remove = L(files).map(Path).partition(lambda f: f.exists() and f.suffix in exts)
	if to_remove: self.code_st.delete_where(where=f'path in ({",".join(to_remove.map(repr))})')
	if not ch: return
	if verbose: print(f'syncing files {ch} .....')
	o = Path(str(ch[0])).parent
	while has_init(o): o = o.parent
	mod_fn = lambda p, n: '.'.join(list(Path(p).relative_to(o).with_suffix('').parts)+[n])
	_get = lambda m,k1,k2: m.get(k1,{}).get(k2,'')
	meta_fn = lambda d: d['metadata'] | dict(mod_name=mod_fn(_get(d,'metadata','path'),_get(d,'metadata','name')))
	fn = lambda d: dict(path=_get(d,'metadata','path'),uploaded_at=_get(d,'metadata','uploaded_at'),metadata=meta_fn(d))
	content = parallel(file_parse, ch, threadpool=True, progress=True).concat().map(lambda d: d | fn(d))
	ex, cont_hash = _content(self.code_st, f=_slug), {_slug(d['content']): d for d in content}
	self.process_repo(filter_keys(cont_hash, not_(in_(ex))).values(), embed, efn=efn)
	for f in ch: self.codedb.q(f'update {self.code_st.name} set uploaded_at=? where path=?',[f.stat().st_mtime, str(f)])
	own = Path(dir).resolve().name
	rows = [dict(from_module=own, to_pkg=dep, n_files=n) for dep,n in count_imp(ch,own).items() if spec(dep)]
	if rows: self.code_rd.insert_all(rows, replace=True)
	if verbose: print('synced repo')

@patch
def prune_old_versions(self:Kosha, pkg:str):
	'Keep only the latest version of a package in the database.'
	if len(vers := self.pkgs(select='version', where=f'name={pkg!r}')) <= 1: return
	latest = sorted(L(vers).attrgot('version'), key=lambda v: tuple(map(int, v.split('.'))))[-1]
	je = lambda k, o='=', v='': f"json_extract(metadata, '$.{k}') {o} {v!r}"
	self.env_st.delete_where(where=f"{je('name')}={pkg!r} AND {je('version')}<>{latest!r}")
	self.pkgs.delete_where(where=f'name={pkg!r} AND version<>{latest!r}')

@patch
def prune_old_pkgs(self:Kosha):
	'Keep only the latest version of each package in the database.'
	L(self.pkgs(select='name')).attrgot('name').map(self.prune_old_versions)

@patch
def pkgs_in_env(self:Kosha, pyproject=False) -> list:
	'Intersection of the packages table with packages installed in the environment.'
	st_pkgs, inst_pkgs = L(self.pkgs(select='name, version')), env_pkg_versions(pyproject=pyproject)
	return st_pkgs.filter(lambda p: p['name'] in inst_pkgs and inst_pkgs[p['name']] == p['version'])

# %% ../nbs/00_core.ipynb #b1c2d3e4f5a6b7c8
_filter_keys = frozenset({'file', 'files', 'path', 'paths', 'package', 'packages', 'lang', 'langs', 'type', 'types'})
_filter_pat = re.compile(r'\b(' + '|'.join(_filter_keys) + r'):(\S+)')
_filter_norm = {'files': 'file', 'paths': 'path', 'packages': 'package', 'langs': 'lang', 'types': 'type'}

def parseq(q: str) -> tuple:
    'Parse key:value filter tokens from a query. Returns (bare_query, filters_dict).'
    filters = defaultdict(list)
    for m in _filter_pat.finditer(q):
        key = _filter_norm.get(m.group(1), m.group(1))
        filters[key].extend(m.group(2).split(','))
    return _filter_pat.sub('', q).strip() or q, filters

# %% ../nbs/00_core.ipynb #0062a079
_glob2like = {'*': '%', '?': '_'}
def _glob_to_like(pat: str) -> str:
    'Convert a glob pattern (*, ?) to a SQL LIKE pattern with surrounding % anchors.'
    p = pat.replace('*', '%').replace('?', '_')
    if not p.startswith('%'): p = '%' + p
    if not p.endswith('%'): p += '%'
    return p

_ext = {'py': '.py', 'js': '.js', 'ts': '.ts', 'jsx': '.jsx', 'tsx': '.tsx', 'rb':'.rb','rs':'.rs','go':'.go',
        'java':'.java','cs':'.cs', 'swift':'.swift','kt':'.kt','lua':'.lua','php':'.php','python':'.py',
        'javascript':'.js','typescript':'.ts','ruby':'.rb','rust':'.rs','golang':'.go'}

def filt2wh(filters: dict, store: str = 'code') -> str | None:
	'Convert a filter dict (from parse_query) to a SQL WHERE clause for the given store (code or env).'
	_get, je = lambda k: filters.get(k,[]), lambda k, o='=', v='': f"json_extract(metadata, '$.{k}') {o} {v!r}"
	list_or = lambda it: ['(%s)'%' OR '.join(ls)] if (ls:=listify(it)) else []
	c, files, paths, langs = [], _get('file'), _get('path'), _get('lang')
	path_wh, lang_chk = list(map(_glob_to_like, files + paths)), list(map(lambda l: _ext.get(l, f'.{l}'), langs))
	lang_wh = list_or(map(lambda lc: je('lang',v=lc), lang_chk))
	if store == 'code': c = list_or(map(lambda p: f'path LIKE {p!r}',path_wh)) + lang_wh
	elif store == 'env':
		c = list_or(map(lambda p: je('path','like',p),path_wh)) + lang_wh
		if pkgs:=_get('package'): c += list_or(map(lambda p: f'package={p!r}',pkgs))
	c += list_or(map(lambda r: je('type',v=r), _get('type')))
	return ' AND '.join(c) if c else None

# %% ../nbs/00_core.ipynb #fed0d571ef995962
@patch
def env_context(self:Kosha,
				q:str,               	# query to search (supports key:value filters)
				emb_q:str=None,     	# query to embed; defaults to bare query after filter parsing
				wide:bool=False,    	# whether to use wide search
				emb_fn=emb_query,		# embedding function
                columns:str='content,metadata',			# comma separated columns string to return from search
                where:str=None,			# additional where clause to filter search results
                efn=embedder,			# embedding function to use for code snippets when updating packages
				sys_wide=True,
				**kw					# additional args to pass to db.search
				) -> L:
	'Code search through the database to find relevant code snippets.'
	raw, fs = parseq(q)
	emb= emb_fn(efn)(emb_q or raw)
	more_p = set(L(self.pkg_context(raw)).map(lambda r: r['metadata']['name']))
	all_p = set(raw.split()).intersection(self.pkgs2consider(sys_wide)).union(more_p)
	for p in all_p: fs['package'].append(p)
	wh = ' AND '.join(map(lambda p: f'({p})', L(filt2wh(fs, 'env'), where).filter(true)))
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if 'metadata' in r else r
	return L(self.envdb.search(pre(raw, wide=wide), emb.tobytes(), columns.split(','), where=wh, **kw)).map(fn)

@patch
def pkgs2consider(self: Kosha, sys_wide=True) -> set:
	'Determine which packages to consider for search based on the intersection of the packages table and the environment.'
	ex_pkgs = merge(*L(self.pkgs(select='name, version')).map(lambda d: {d['name']: d['version']}))
	if sys_wide: return ex_pkgs.keys()
	env_pkgs = env_pkg_versions()
	return {p for p in env_pkgs if p in ex_pkgs and env_pkgs[p] == ex_pkgs[p]}

# %% ../nbs/00_core.ipynb #12beefe0bbdabfd8
@patch
def repo_context(self:Kosha,
                q:str,                          # query to search (supports key:value filters)
                emb_q:str=None,                 # query to embed; defaults to bare query after filter parsing
                wide:bool=False,                # use wide (OR) FTS search
                emb_fn=emb_query,               # embedding function
                columns:str='content,path,metadata', # columns to return
                where:str=None,                 # extra SQL filter
                efn=embedder,                   # embedding function to use for code snippets when updating repo
                **kw                            # additional args to pass to db.search
) -> L:
	'Semantic + keyword search through indexed repo code.'
	raw, fs = parseq(q)
	emb = emb_fn(efn)(emb_q or raw)
	wh = filt2wh(fs, 'code')
	if where and wh: wh = f'({where}) AND ({wh})'
	elif where: wh = where
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if 'metadata' in r else r
	return L(self.codedb.search(pre(raw, wide=wide), emb.tobytes(), columns.split(','), where=wh, **kw)).map(fn)

@patch
async def awatch_repo(self:Kosha, dir:Path=None, **kw):
	'Async watcher: re-indexes changed files on every watchfiles event.'
	from watchfiles import awatch
	dir = Path(dir or self.root)
	async for changes in awatch(str(dir)): self.update_repo(dir, files=L({c[1] for c in changes}), **kw)

@patch
def watch_repo(self:Kosha, dir:Path=None, **kw):
	'Block and watch repo for changes, re-indexing incrementally. Ctrl-C to stop.'
	arun(self.awatch_repo(dir, **kw))

# %% ../nbs/00_core.ipynb #b739867c9dc3b47e
@patch
def pkg_context(self:Kosha,
                q:str, # the search query
                limit:int=10, # limits
                efn=embedder
                ) -> L:
	'FTS5+vector search over package descriptions in pkg_store.'
	emb = emb_query(efn)(q).tobytes()
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if isinstance(r.get('metadata'), str) else r
	return L(self.envdb.search(q, emb, columns=['content','metadata'], table_name='pkg_store', limit=limit)).map(fn)
