"""Kosha is a tool for building a context for code generation based on your repo and environment.
It uses a vector database to store code snippets and their embeddings, allowing you to search for relevant code based
on natural language queries.
The core functionality includes managing the database, updating package metadata, embedding code snippets,
and performing context-aware searches."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['cr_instr', 'model', 'strict_skip_folder_re', 'strict_skip_file_re', 'parse', 'repo_root', 'mv_skill_md', 'arun',
           'pkg_trans_deps', 'env_pkg_versions', 'embedder', 'static_embedder', 'emb_doc', 'emb_query', 'Kosha',
           'pkg_url', 'pkg_doc', 'has_init', 'enrich_chunks', 'embed_chunk', 'process_content', 'count_imp', 'parseq',
           'filt2wh']

# %% ../nbs/00_core.ipynb #69029d72f94a2fdc
import ast, os, re
from ast import get_source_segment as gs
from collections import defaultdict, Counter
from apswutils.utils import hash_record
from importlib.metadata import version as v, metadata as meta, distribution as dist
from chonkie import AutoEmbeddings
from fastcore.all import (Path, first, patch, timed_cache, L, parallel, merge, AttrDict,
                          filter_keys, not_, in_, listify, true, fdelegates, parallel_async,type2str)
from fastcore.xdg import xdg_data_home
from tqdm import tqdm
from json import loads as jl
from litesearch import *

# %% ../nbs/00_core.ipynb #bfe18701edf5102
@timed_cache(maxsize=512)
def parse(code=None, p=None):
    "Parse source, tag parents, return (tree, imp, top_fns, all_fns). Cached — called freely."
    if not code and not p: return None, {}, set(), set()
    try: tree = ast.parse(Path(p).read_text(errors='replace') if not code else code)
    except SyntaxError: return None, {}, set(), set()
    [setattr(c,'parent',n) for n in ast.walk(tree) for c in ast.iter_child_nodes(n)]
    is_top = lambda n: isinstance(getattr(n,'parent',None), ast.Module)
    is_fn  = lambda n: isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef,ast.ClassDef))
    is_nm  = lambda n: isinstance(n, ast.Name)
    imp, imp2mod = {}, {}
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            for a in n.names: imp[a.asname or a.name.split('.')[0]] = a.name.split('.')[0]
        elif isinstance(n, ast.ImportFrom):
            pkg = (n.module or '').split('.')[0]
            for a in n.names:
                if a.name != '*':
	                imp[a.asname or a.name] = pkg
	                if n.module: imp2mod[a.asname or a.name] = f'{n.module}.{a.name}'
                else: imp.setdefault(f'*{pkg}', pkg)
    top = {n.name for n in ast.walk(tree) if is_fn(n) and is_top(n)}
    ca  = {nm for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.value,ast.Call)
           for t in n.targets
           for nm in ([t.id] if is_nm(t) else [e.id for e in t.elts if is_nm(e)] if isinstance(t,ast.Tuple) else [])}
    return tree, imp, top, top | ca, imp2mod

# %% ../nbs/00_core.ipynb #d4532509b3f08ee1
def repo_root() -> Path:
	'Find the root of the current git repository, or None if not in a repo.'
	return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None) -> None:
	'Copy bundled SKILL.md to skill directories.'
	base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
	if not (src := base.joinpath('SKILL.md')).exists(): return
	root = dir or repo_root() or '.'
	ts = [Path(root)/'.agents/skills/kosha/SKILL.md', Path('.claude/skills/kosha/SKILL.md')]
	if dry_run: print(f'Copying {src} to: {list(map(str,ts))}')
	else: [p.mk_write(src.read_text(encoding='utf-8'))for p in ts]
	print(f'Installed → {list(map(str,ts))}')

# %% ../nbs/00_core.ipynb #8b67e1dd013da45b
def arun(coro) -> any:
	'Run an async coroutine from sync code, even if already inside an event loop'
	import asyncio
	try: asyncio.get_running_loop()
	except RuntimeError: return L(asyncio.run(coro))
	import concurrent.futures
	with concurrent.futures.ThreadPoolExecutor() as pool: return L(pool.submit(asyncio.run, coro).result())

# %% ../nbs/00_core.ipynb #e5909953befa8a39
_req_nm = re.compile(r'^[\w][\w.-]*')

def pkg_trans_deps(seeds:list, depth:int=2) -> L:
	'BFS over importlib.metadata requires: return seeds + all transitive deps up to depth levels (installed only, no optional extras).'
	seen, frontier = set(seeds), set(seeds)
	for _ in range(depth):
		nxt = set()
		for pkg in frontier:
			try:
				for req in (dist(pkg).requires or []):
					if 'extra ==' in req: continue
					if (m := _req_nm.match(req)) and spec(m.group(0)): nxt.add(m.group(0))
			except Exception: pass
		nxt -= seen
		if not nxt: break
		seen |= nxt; frontier = nxt
	return L(seen)

# %% ../nbs/00_core.ipynb #9fab4c1d39a247e3
def env_pkg_versions(pyproject=True, depth:int=1) -> dict:
	'''Get a dict of installed package versions using importlib.metadata.
	passing depth traverse multiple layers of dependencies'''
	pkgs = installed_packages(pyproject=pyproject)
	if pyproject and depth: pkgs = pkg_trans_deps(pkgs, depth)
	return merge(*pkgs.map(lambda p: {dist(p).metadata['Name']: dist(p).version}))

# %% ../nbs/00_core.ipynb #3ccb8e947caec348
cr_instr = AttrDict(query="Represent this query for searching relevant code: {text}", document="{text}")
model = AttrDict(model='mrsladoje/CodeRankEmbed-onnx-int8', onnx_path='onnx/model.onnx', prompt=cr_instr)
strict_skip_folder_re = r'^[._]|^(?:tests?|examples?|docs?|build|dist)$'
strict_skip_file_re = r'^[._]|^(?:setup\.py|conftest\.py)$'

@timed_cache(3600*24)
def embedder(
    emb_model=model  # model config AttrDict (model name, onnx_path, prompt instructions)
) -> 'FastEncode':
    "Load or return cached CodeRankEmbed ONNX document embedder (24h TTL)."
    try: return FastEncode(emb_model, parallel=8, batch_size=64)
    except Exception: return FastEncode(emb_model, parallel=1, batch_size=64)

@timed_cache(3600*24)
def static_embedder(
    emb_model='minishlab/potion-retrieval-32M'  # HuggingFace model id for static embeddings
) -> 'AutoEmbeddings':
    "Load or return cached static (potion-retrieval) embedder (24h TTL)."
    return AutoEmbeddings().get_embeddings(emb_model)

def emb_doc(
    e  # embedder factory — callable returning a FastEncode or AutoEmbeddings instance
):
    "Curry an embedder factory into a document-embedding function `t -> embedding`."
    return lambda t: e().encode_document(t) if isinstance(e(), FastEncode) else e().embed_batch(listify(t))

def emb_query(
    e  # embedder factory — callable returning a FastEncode or AutoEmbeddings instance
):
    "Curry an embedder factory into a query-embedding function `t -> embedding`."
    return lambda t: e().encode_query(t) if isinstance(e(), FastEncode) else e().embed_batch(listify(t))

# %% ../nbs/00_core.ipynb #8511999ac2824a0b
class Kosha:
	'Kosha allows you to build a context for code generation based on your repo and environment.'
	def __init__(self, dir: Path = None, install_skill: bool = False, xdg_dir: Path = None):
		self.root, self.xdg = Path(dir or repo_root() or '.'), xdg_dir or xdg_data_home()
		if install_skill: mv_skill_md(dir=self.root, dry_run=False)
		self.cp, self.ce = self.root.joinpath('.kosha','code.db'), self.xdg.joinpath('kosha','env.db')
		for p in (self.cp, self.ce): p.parent.mkdir(parents=True, exist_ok=True)
		self.codedb, self.envdb = database(self.cp), database(self.ce)
		self.code_st,self.env_st = self.codedb.get_store(path=str,hash=True),self.envdb.get_store(package=str,hash=True)
		self.pkg_st, self.pkgs = self.envdb.get_store('pkg_store', hash=True), self.envdb.t.packages
		self.env_pd, self.code_rd = self.envdb.t.pkg_deps, self.codedb.t.repo_deps
		self.pkgs.create(name=str, version=str, summary=str, uploaded_at=float, pk=['name','version'],
			 defaults=dict(uploaded_at='CURRENT_TIMESTAMP'), if_not_exists=True)
		self.env_pd.create(from_pkg=str, to_pkg=str, n_modules=int, if_not_exists=True, pk=['from_pkg','to_pkg'])
		self.code_rd.create(from_module=str, to_pkg=str, n_files=int, if_not_exists=True, pk=['from_module','to_pkg'])

# %% ../nbs/00_core.ipynb #pkg_url_a1b2c3d4
def pkg_url(pkg: str) -> str | None:
    'Return best web URL for pkg from importlib.metadata: Source Code > Repository > Home-page > first Project-URL.'
    m, urls = meta(pkg), {}
    for e in (m.get_all('Project-URL') or []):
        label, _, u = e.partition(',')
        urls[label.strip().lower()] = u.strip()
    return (urls.get('source code') or urls.get('repository') or urls.get('source') or
            urls.get('github') or m.get('Home-page') or next(iter(urls.values()), None))


# %% ../nbs/00_core.ipynb #pkg_store_helpers_a1b2
def pkg_doc(pkg) -> dict:
	'Build pkg_store content dict: content=summary+readme, metadata=json.'
	m = meta(pkg)
	_get, _req_re, fn = lambda k: m.get(k,''), re.compile(r'^[\w-]+'), lambda rm: rm.group(0).lower().replace('-','_')
	reqs = ' '.join({fn(rm) for r in (m.get_all('Requires-Dist') or []) if (rm:=_req_re.match(r))})
	summary = _get('Summary')
	cont = summary+'\n'+(m.get_payload() or _get('Description') or '')[:2000].strip()
	return dict(content=cont, metadata=dict(name=pkg, version=v(pkg), keywords=_get('Keywords'),
	                                        requires=reqs, summary=summary, url=pkg_url(pkg)))


# %% ../nbs/00_core.ipynb #5e6e5dace1c5fe8d
def has_init(d: Path) -> bool:
	'True if dir is a Python package root: has __init__.py or a C-extension __init__*.so.'
	return (d / '__init__.py').exists() or bool(list(d.glob('__init__*.so')))

# %% ../nbs/00_core.ipynb #enrich_chunks_a1b2c3d4
def enrich_chunks(content: L) -> L:
	'Set public_api+docstring flags on non-assign chunks and explode ClassDefs into method sub-chunks.'
	_m, _c = lambda d, k: d.get('metadata',{}).get(k,''), lambda d: d.get('content','')
	assigns, non_assigns = content.partition(lambda d: d['metadata'].get('type','') in ('Assign','AnnAssign'))
	chk = lambda e: isinstance(e, ast.Constant) and isinstance(e.value, str)
	def _get__all(d):
		try: return set(L(ast.parse(_c(d)).body[0].value.elts).filter(chk).attrgot('value'))
		except: return set()
	all_map = merge(*assigns.filter(lambda d: '__all__' in _c(d)).map(lambda d: {_m(d,'path'): _get__all(d)}))
	fwa = set(all_map)
	def _enrich(d):
		nm, pth = _m(d,'name'), _m(d,'path')
		try: doc = ast.get_docstring(ast.parse(_c(d)).body[0])
		except: doc = None
		return d | {'metadata': d['metadata'] | dict(docstring=doc,
			public_api=(nm in all_map[pth]) if pth in fwa else bool(nm and not nm.startswith('_')))}
	def _cls_methods(d):
		src, m = _c(d), d['metadata']
		try: cls = ast.parse(src).body[0]
		except: return L()
		if not isinstance(cls, ast.ClassDef): return L()
		pub, mod, off = m.get('public_api',False), m.get('mod_name',''), (m.get('lineno') or 1)-1
		is_fn = lambda n: isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and gs(src, n)
		mk = lambda n: d | {'content': gs(src, n).strip(), 'metadata': m | dict(
			name=n.name, type=type2str(n.__class__), mod_name=f'{mod}.{n.name}',
			public_api=pub and (not n.name.startswith('_') or n.name.startswith('__')),
			docstring=ast.get_docstring(n), lineno=off+n.lineno, end_lineno=off+(n.end_lineno or n.lineno))}
		return L(cls.body).filter(is_fn).map(mk)
	enriched = arun(parallel_async(_enrich, non_assigns)).concat()
	return enriched + enriched.filter(lambda d: d['metadata'].get('type')=='ClassDef').map(_cls_methods).concat()

# %% ../nbs/00_core.ipynb #cd93d2c15ca33a8d
os.environ['TOKENIZERS_PARALLELISM']='false'  # to suppress warnings from tokenizers
@patch
def nuke(self:Kosha):
	'Reset the databases by dropping all tables.'
	for p in (self.cp, self.ce): p.parent.delete()

@patch
def _is_pkg_ingested(self:Kosha, pkg:str) -> bool:
	'Check if a package is already ingested and up-to-date.'
	return first(self.pkgs(select='name, version', where=f'name={pkg!r} and version={v(pkg)!r}'))

def embed_chunk(chunk:list|L,emb_fn=emb_doc, efn=embedder):
	'Embed a list of code chunks using emb_f'
	if not (chunk): return
	c = [b['content'] for b in chunk if b['content'] and b['content'].strip()]
	if not c: return
	for e,b in zip(emb_fn(efn)(c),chunk): b['embedding'] = e.tobytes()
	return chunk

def process_content(store, content:L, embed:bool=True, efn=embedder):
	'Embed chunks and upsert into store; no-op if content is empty.'
	if not content: return
	if embed: content = embed_chunk(content, efn=efn)
	return store.insert_all(content, upsert=True, hash_id='id', hash_id_columns=['content'])

@patch
@fdelegates(process_content)
def process_env(self:Kosha, content=None, reembed=False, **kwargs):
	'Embed all documents in the env store, or only those without embeddings if reembed=False.'
	content = content or self.env_st(where=f'embedding is NULL' if not reembed else None)
	return process_content(self.env_st, content, **kwargs)

def _slug(s): return hash_record({"content": s}) if s else None

def _content(store, where:str=None, f=None):
	'Helper to retrieve content from a store with optional filtering and transformation.'
	c=L(store(select='content', where=where)).filter(lambda c: c['content'] and c['content'].strip()).attrgot('content')
	return c if not f else L(c).map(f)

def count_imp(files, own:str='') -> Counter:
	'External top-level imports from a source-string iterable. Reuses cached _parse.'
	c, fn = Counter(), lambda p: p and p!=own and p[0]!='_'
	def do(f): c.update(set(L(parse(p=f)[1].values()).filter(fn)))
	L(files).map(do)
	return c

@patch
@fdelegates(pkg2chunks)
def update_pkg(self:Kosha, pkg:str, embed=True, exts=code_exts, efn=embedder, verbose=True, force=False, **kwargs):
    'Update package metadata in the packages table.'
    assert (o:= spec(pkg)), f'pkg {pkg} is not in environment'
    if verbose: print(f'updating pkg: {pkg} ...')
    ep = self._is_pkg_ingested(pkg)
    if ep and len(self.env_st(where=f'package={pkg!r}')) > 0:
        if verbose: print(f'package {ep} already loaded.')
        if not force: return
        print(f'forcing an update to pkg {ep}')
    pkg_par = Path(o.origin).parent.parent if o.origin else Path(o.submodule_search_locations[0])
    mod_fn = lambda p, n: '.'.join(list(Path(p).relative_to(pkg_par).with_suffix('').parts) + ([n] if n else []))
    _get = lambda o,k1=None: o.get('metadata').get(k1,'')
    meta_fn = lambda d: d['metadata'] | dict(mod_name=mod_fn(_get(d,'path'), _get(d,'name') or None),
                                             package=pkg, version=v(pkg))
    fn = lambda d: dict(package=pkg, uploaded_at=_get(d,'uploaded_at'), metadata=meta_fn(d))
    content = parallel(file_parse, pkg2files(pkg, exts=exts, **kwargs), threadpool=True, assigns=True,
                       imports=kwargs.pop('imports', False)).filter(true).concat().map(lambda d: d | fn(d))
    content, doc = enrich_chunks(content), pkg_doc(pkg)
    ex = L() if force else _content(self.env_st, where=f'package={pkg!r}', f=_slug)
    cont_hash = {_slug(d['content']): d for d in content}
    if del_ids:=set(ex).difference(cont_hash.keys()): self.env_st.delete_where(where='id in ("%s")'%'","'.join(del_ids))
    ch = filter_keys(cont_hash, not_(in_(ex))).values()
    if ch and self.process_env(ch, embed=embed, efn=efn):
        counts = count_imp(pkg2files(pkg, exts=['.py']),pkg.replace('-','_').split('.')[0])
        rows = [dict(from_pkg=pkg, to_pkg=dep, n_modules=n) for dep,n in counts.items() if spec(dep)]
        if rows: self.envdb.t.pkg_deps.insert_all(rows, replace=True)
    if verbose: print(f'updated pkg: {pkg} with {len(ch)} new/changed chunks, {len(ex)-len(ch)} unchanged, '
              f'{len(ex)-len(cont_hash)} removed')
    return self.pkgs.insert(dict(name=pkg, version=v(pkg), summary=_get(doc,'summary')), ignore=True)

@patch
def rm_pkg(self:Kosha, pkg:str, ver:str=None):
	'Remove a package and its code snippets from the database.'
	wh = f'package={pkg!r} AND version={ver!r}' if ver else f'package={pkg!r}'
	for t in [self.env_st, self.pkgs]: t.delete(where=wh)
	self.pkg_st.delete_where(where=f"json_extract(metadata,'$.name')={pkg!r}")
	self.env_pd.delete_where(where=f'from_pkg={pkg!r}')
	self.pkgs.delete_where(where=f'name={pkg!r}')

@patch
def process_repo(self:Kosha, content=None, reembed=False, **kwargs):
	'Embed all documents in the code store, or only those without embeddings if reembed=False.'
	content = content or self.code_st(where=f'embedding is NULL' if not reembed else None)
	return process_content(self.code_st, content, **kwargs)

@patch
def update_pkgs(self:Kosha,
    pkgs:str|list=None, # packages to sync; None syncs all installed env packages
    embed=True,         # embed chunks after indexing
    exts=code_exts,     # file extensions to include
    efn=embedder,       # embedding function
    verbose=True,       # print progress
    force=False,        # reindex even if package version already loaded
    **kwargs            # forwarded to update_pkg
):
	'Sync installed packages into the env store; if pkgs is None, syncs all env packages.'
	pkgs = set(pkgs).intersection(env_pkg_versions(pyproject=False)) if pkgs else set(env_pkg_versions())
	if verbose: print(f'loading pkgs {pkgs} ......')
	kw = dict(embed=embed, exts=exts, efn=efn, verbose=verbose, force=force, **kwargs)
	for pkg in tqdm(pkgs, desc='Updating packages', unit='pkg'): self.update_pkg(pkg, **kw)

@patch
@fdelegates(dir2files)
def update_repo(self:Kosha,
				dir:Path=None,    # directory to index; defaults to repo root
				embed:bool=True,  # embed chunks after parsing
				files:L=None,     # specific paths to (re)index; None = full sync
                exts:str=code_exts,
                efn=embedder,       # embedding function to use for code snippets
                verbose=True,       # verbose
                force=False,        # reindex all files regardless of mtime
				**kwargs              # extra args forwarded to dir2files
				):
	'Index or update repo code chunks. Pass files= for incremental update (e.g. from watcher).'
	dir = Path(dir or self.root)
	if files is None:
		known = {r['path']: r['uploaded_at'] for r in self.code_st(select='path, uploaded_at') if r['path']}
		all_files = dir2files(str(dir), strict_skip_file_re, strict_skip_folder_re,exts=exts, **kwargs)
		to_remove = L(known.keys()).filter(lambda k: k not in all_files.map(str)).concat()
		ch = all_files if force else L(all_files).filter(lambda f: str(f) not in known or known[str(f)] != f.stat().st_mtime)
	else: ch,to_remove = L(files).map(Path).partition(lambda f: f.exists() and f.suffix in exts)
	if to_remove: self.code_st.delete_where(where=f'path in ({",".join(to_remove.map(repr))})')
	if not ch: return
	if verbose: print(f'syncing files {ch} .....')
	o = Path(str(ch[0])).parent
	while has_init(o): o = o.parent
	mod_fn = lambda p, n: '.'.join(list(Path(p).relative_to(o).with_suffix('').parts)+([n] if n else []))
	_get = lambda m,k1,k2: m.get(k1,{}).get(k2,'')
	meta_fn = lambda d: d['metadata'] | dict(mod_name=mod_fn(_get(d,'metadata','path'),_get(d,'metadata','name')))
	fn = lambda d: dict(path=_get(d,'metadata','path'),uploaded_at=_get(d,'metadata','uploaded_at'),metadata=meta_fn(d))
	content = enrich_chunks(parallel(file_parse, ch, threadpool=True, progress=True, assigns=True).concat().map(
		lambda d: d | fn(d)))
	pl = ','.join(map(repr, L(ch).map(str)))
	ex = L() if force else _content(self.code_st, where=f'path IN ({pl})', f=_slug)
	cont_hash = {_slug(d['content']): d for d in content}
	if dids := set(ex).difference(cont_hash.keys()): self.code_st.delete_where(where='id in ("%s")' % '","'.join(dids))
	self.process_repo(filter_keys(cont_hash, not_(in_(ex))).values(), embed, efn=efn)
	for f in ch: self.codedb.q(f'update {self.code_st.name} set uploaded_at=? where path=?',[f.stat().st_mtime, str(f)])
	own = Path(dir).resolve().name
	rows = [dict(from_module=own, to_pkg=dep, n_files=n) for dep,n in count_imp(ch,own).items() if spec(dep)]
	if rows: self.code_rd.insert_all(rows, replace=True)
	if verbose: print('synced repo')

@patch
def prune_old_versions(self:Kosha, pkg:str):
	'Keep only the latest version of a package in the database.'
	if len(vers := self.pkgs(select='version', where=f'name={pkg!r}')) <= 1: return
	latest = sorted(L(vers).attrgot('version'), key=lambda v: tuple(map(int, v.split('.'))))[-1]
	je = lambda k, o='=', v='': f"json_extract(metadata, '$.{k}') {o} {v!r}"
	self.env_st.delete_where(where=f"{je('name')}={pkg!r} AND {je('version')}<>{latest!r}")
	self.pkgs.delete_where(where=f'name={pkg!r} AND version<>{latest!r}')

@patch
def prune_old_pkgs(self:Kosha):
	'Keep only the latest version of each package in the database.'
	L(self.pkgs(select='name')).attrgot('name').map(self.prune_old_versions)

@patch
def pkgs_in_env(self:Kosha, pyproject=False) -> list:
	'Intersection of the packages table with packages installed in the environment.'
	st_pkgs, inst_pkgs = L(self.pkgs(select='name, version')), env_pkg_versions(pyproject=pyproject)
	return st_pkgs.filter(lambda p: p['name'] in inst_pkgs and inst_pkgs[p['name']] == p['version'])

# %% ../nbs/00_core.ipynb #b1c2d3e4f5a6b7c8
_filter_keys = frozenset({'file', 'files', 'path', 'paths', 'package', 'packages', 'lang', 'langs', 'type', 'types'})
_filter_pat = re.compile(r'\b(' + '|'.join(_filter_keys) + r'):(\S+)')
_filter_norm = {'files': 'file', 'paths': 'path', 'packages': 'package', 'langs': 'lang', 'types': 'type'}

def parseq(q: str) -> tuple:
    'Parse key:value filter tokens from a query. Returns (bare_query, filters_dict).'
    filters = defaultdict(list)
    for m in _filter_pat.finditer(q):
        key = _filter_norm.get(m.group(1), m.group(1))
        filters[key].extend(m.group(2).split(','))
    return _filter_pat.sub('', q).strip() or q, filters

# %% ../nbs/00_core.ipynb #0062a079
_glob2like = {'*': '%', '?': '_'}
def _glob_to_like(pat: str) -> str:
    'Convert a glob pattern (*, ?) to a SQL LIKE pattern with surrounding % anchors.'
    p = pat.replace('*', '%').replace('?', '_')
    if not p.startswith('%'): p = '%' + p
    if not p.endswith('%'): p += '%'
    return p

_ext = {'py': '.py', 'js': '.js', 'ts': '.ts', 'jsx': '.jsx', 'tsx': '.tsx', 'rb':'.rb','rs':'.rs','go':'.go',
        'java':'.java','cs':'.cs', 'swift':'.swift','kt':'.kt','lua':'.lua','php':'.php','python':'.py',
        'javascript':'.js','typescript':'.ts','ruby':'.rb','rust':'.rs','golang':'.go'}

def filt2wh(filters: dict, store: str = 'code') -> str | None:
	'Convert a filter dict (from parse_query) to a SQL WHERE clause for the given store (code or env).'
	_get, je = lambda k: filters.get(k,[]), lambda k, o='=', v='': f"json_extract(metadata, '$.{k}') {o} {v!r}"
	list_or = lambda it: ['(%s)'%' OR '.join(ls)] if (ls:=listify(it)) else []
	c, files, paths, langs = [], _get('file'), _get('path'), _get('lang')
	path_wh, lang_chk = list(map(_glob_to_like, files + paths)), list(map(lambda l: _ext.get(l, f'.{l}'), langs))
	lang_wh = list_or(map(lambda lc: je('lang',v=lc), lang_chk))
	if store == 'code': c = list_or(map(lambda p: f'path LIKE {p!r}',path_wh)) + lang_wh
	elif store == 'env':
		c = list_or(map(lambda p: je('path','like',p),path_wh)) + lang_wh
		if pkgs:=_get('package'): c += list_or(map(lambda p: f'package={p!r}',pkgs))
	c += list_or(map(lambda r: je('type',v=r), _get('type')))
	return ' AND '.join(c) if c else None

# %% ../nbs/00_core.ipynb #fed0d571ef995962
@patch
def env_context(self:Kosha,
				q:str,               	# query to search (supports key:value filters)
				emb_q:str=None,     	# query to embed; defaults to bare query after filter parsing
				wide:bool=False,    	# whether to use wide search
				emb_fn=emb_query,		# embedding function
                columns:str='content,metadata,package',			# comma separated columns string to return from search
                where:str=None,			# additional where clause to filter search results
                efn=embedder,			# embedding function to use for code snippets when updating packages
				sys_wide=True,
				**kw					# additional args to pass to db.search
				) -> L:
	'Code search through the database to find relevant code snippets.'
	raw, fs = parseq(q)
	emb= emb_fn(efn)(emb_q or raw)
	all_p = set(raw.split()).intersection(self.pkgs2consider(sys_wide)) if 'package' not in fs else []
	for p in all_p: fs['package'].append(p)
	wh = ' AND '.join(map(lambda p: f'({p})', L(filt2wh(fs, 'env'), where).filter(true)))
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if 'metadata' in r else r
	return L(self.envdb.search(pre(raw, wide=wide), emb.tobytes(), columns.split(','), where=wh, **kw)).map(fn)

@patch
def pkgs2consider(self: Kosha, sys_wide=True) -> set:
	'Determine which packages to consider for search based on the intersection of the packages table and the environment.'
	ex_pkgs = merge(*L(self.pkgs(select='name, version')).map(lambda d: {d['name']: d['version']}))
	if sys_wide: return ex_pkgs.keys()
	env_pkgs = env_pkg_versions()
	return {p for p in env_pkgs if p in ex_pkgs and env_pkgs[p] == ex_pkgs[p]}

# %% ../nbs/00_core.ipynb #12beefe0bbdabfd8
@patch
def repo_context(self:Kosha,
                q:str,                          # query to search (supports key:value filters)
                emb_q:str=None,                 # query to embed; defaults to bare query after filter parsing
                wide:bool=False,                # use wide (OR) FTS search
                emb_fn=emb_query,               # embedding function
                columns:str='content,path,metadata', # columns to return
                where:str=None,                 # extra SQL filter
                efn=embedder,                   # embedding function to use for code snippets when updating repo
                **kw                            # additional args to pass to db.search
) -> L:
	'Semantic + keyword search through indexed repo code.'
	raw, fs = parseq(q)
	emb = emb_fn(efn)(emb_q or raw)
	wh = filt2wh(fs, 'code')
	if where and wh: wh = f'({where}) AND ({wh})'
	elif where: wh = where
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if 'metadata' in r else r
	return L(self.codedb.search(pre(raw, wide=wide), emb.tobytes(), columns.split(','), where=wh, **kw)).map(fn)

@patch
async def awatch_repo(self:Kosha, dir:Path=None, **kw):
	'Async watcher: re-indexes changed files on every watchfiles event.'
	from watchfiles import awatch
	dir = Path(dir or self.root)
	async for changes in awatch(str(dir)): self.update_repo(dir, files=L({c[1] for c in changes}), **kw)

@patch
def watch_repo(self:Kosha, dir:Path=None, **kw):
	'Block and watch repo for changes, re-indexing incrementally. Ctrl-C to stop.'
	arun(self.awatch_repo(dir, **kw))

# %% ../nbs/00_core.ipynb #b739867c9dc3b47e
@patch
def pkg_context(self:Kosha,
                q:str, # the search query
                limit:int=10, # limits
                efn=embedder
                ) -> L:
	'FTS5+vector search over package descriptions in pkg_store.'
	emb = emb_query(efn)(q).tobytes()
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if isinstance(r.get('metadata'), str) else r
	return L(self.envdb.search(q, emb, columns=['content','metadata'], table_name='pkg_store', limit=limit)).map(fn)
