"""CodeGraph: call-graph layer for kosha, backed by graph.db. Augments semantic search with structural traversal.

Docs: https://vedicreader.github.io/kosha/graph.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_graph.ipynb.

# %% auto #0
__all__ = ['CodeGraph', 'dyn_edges', 'static_edges', 'is_symbol_query', 'rank_results', 'is_sys_pkg']

# %% ../nbs/01_graph.ipynb #ff995efe
import ast, re, os, builtins, numpy as np
from json import loads as jl
from collections import defaultdict
from litesearch.core import database, rrf_all, rerank_hits
from litesearch.data import *
from fastcore.all import (Path, L, patch, groupby, parallel_async, tuplify, first, fdelegates, globtastic, bind, true, dict2obj,
                          listify, filter_keys, in_, chunked, noop, parallel, not_)
from .core import arun, Kosha, parse, has_init, imp_root, env_pkg_versions, _pkg_name, repo_skip_folder_re,strict_skip_file_re
from ast_grep_py import SgRoot
from tqdm import tqdm


# %% ../nbs/01_graph.ipynb #af482cb1
class CodeGraph:
	'''Call graph builder and query engine. Uses ast-grep for static analysis and custom AST parsing for dynamic edges.
	Stores everything in a SQLite database.
	'''
	def __init__(self, path: str | Path = ':memory:'):
		self.path = path
		self.db = database(path)
		ge, gn, cd, fi = self.db.t.graph_edges, self.db.t.graph_nodes, self.db.t.co_dispatch, self.db.t.file_index
		pa, gm = self.db.t.pending_attr_calls, self.db.t.graph_meta
		pa.create(caller=str, method=str, pkgs=str, if_not_exists=True, pk='caller,method')
		ge.create(caller=str, callee=str, kind=str, confidence=float, if_not_exists=True, pk=('caller','callee','kind'))
		gn.create(node=str,flavor=str,file=str,method=str,pagerank=float,in_degree=int,out_degree=int,if_not_exists=True,pk='node')
		if 'method' not in gn.columns_dict: gn.add_column('method', str)
		cd.create(group_id=int, node=str, if_not_exists=True)
		fi.create(path=str, root=str, source_hash=str, last_analyzed_at=float, if_not_exists=True, pk='path')
		if 'source_hash' not in fi.columns_dict: fi.add_column('source_hash', str)
		gm.create(k=str, v=float, if_not_exists=True, pk='k')
		fi.create_index(['root'], if_not_exists=True)
		fi.create_index(['source_hash'], if_not_exists=True)
		gn.create_index(['method'], if_not_exists=True)
		self.ge, self.gn, self.cd, self.fi, self.pa, self.gm = ge, gn, cd, fi, pa, gm

	def _meta(self, k, v=None):
		'Read `k`, or write `v` to it and return it.'
		if v is not None: self.gm.insert(dict(k=k, v=v), replace=True); return v
		r = first(self.gm(where='k=?', where_args=[k]))
		return r['v'] if r else None

	def nuke(self): [t.drop() for t in (self.ge, self.gn, self.cd, self.fi, self.gm)]


# %% ../nbs/01_graph.ipynb #82f10dfa
_reg_re = re.compile(
    r'^(add|register|include|on|connect|mount|sub(scribe)?|listen|use|route|handle|hook|attach|bind|plug|get|post|'
    r'put|delete|patch|head|options|before|after|middleware)(_\w+)?$', re.IGNORECASE)
_conn = {'connect', 'setup', 'register', 'init_app', 'create_app', 'mount','configure','bootstrap','install','activate'}
_web_pkg = {'fasthtml', 'flask', 'fastapi', 'starlette', 'django', 'aiohttp','sanic','tornado','litestar','blacksheep'}

# %% ../nbs/01_graph.ipynb #578eec3e302e059c
def _root(n):
	while isinstance(n, ast.Attribute): n = n.value
	return n.id if isinstance(n, ast.Name) else None

def _conf(root, verb, imp):
	pkg = imp.get(root) or next((v for k,v in imp.items() if k.startswith('*')), None)
	return 0.95 if pkg in _web_pkg else 0.75 if _reg_re.match(verb or '') else 0.5

def _e(caller, callee, kind, conf): return {'caller':caller,'callee':callee,'kind':kind,'confidence':conf}

def _dec_edges(n, mod, imp):
	fn = f"{mod}.{n.name}"
	return [_e(f"{mod}.{r}", fn, 'decorator', _conf(r, inner.attr, imp))
	        for dec in n.decorator_list
	        for inner in [dec.func if isinstance(dec,ast.Call) else dec]
	        if isinstance(inner,ast.Attribute) and (r := _root(inner))]

def _conn_edges(n, mod):
	if n.name not in _conn or not n.args.args: return []
	param, fn = n.args.args[0].arg, f'{mod}.{n.name}'
	return [_e(fn, f'{mod}.{a.id}', 'connect_body', 0.9)
	        for child in ast.walk(n)
	        if isinstance(child,ast.Call) and isinstance(child.func,ast.Attribute)
	        and _root(child.func) == param
	        for a in child.args if isinstance(a,ast.Name)]

def _reg_edges(n, mod, imp, all_fns):
	if not (isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and _reg_re.match(n.func.attr)): return []
	root = _root(n.func) or 'unknown'
	return [_e(f"{mod}.{root}", f"{mod}.{a.id}", 'registration', _conf(root, n.func.attr, imp))
	        for a in n.args if isinstance(a,ast.Name) and a.id in all_fns]

def _co_edges(n, mod, top_fns):
	if not (isinstance(n,ast.Assign) and isinstance(getattr(n,'parent',None), ast.Module)): return []
	val = n.value
	grp = ([v.id for v in val.values if isinstance(v,ast.Name) and v.id in top_fns] if isinstance(val,ast.Dict) else
	       [e.id for e in val.elts if isinstance(e,ast.Name) and e.id in top_fns]
	       if isinstance(val,(ast.List,ast.Tuple)) else [])
	return [_e(f"{mod}.{a}",f"{mod}.{b}",'co_dispatch',0.8) for i,a in enumerate(grp) for b in grp[i+1:]]

def _patch_edges(n, mod):
	'fastcore @patch: @patch def fn(self:Class) → Class gains fn as method.'
	if not any(('patch' in ast.unparse(d)) for d in n.decorator_list): return []
	if not ((args := n.args.args) and (ann:=args[0].annotation)): return []
	tgts = ([ast.unparse(ann.left), ast.unparse(ann.right)]
			   if isinstance(ann, ast.BinOp) and isinstance(ann.op, ast.BitOr)
			   else [ast.unparse(ann)])
	return [_e(f"{mod}.{t}", f"{mod}.{n.name}", 'patch', 0.9) for t in tgts]

def _delegates_edges(n, mod):
	'fastcore @delegates(target): fn wraps target\'s signature — structural dependency.'
	is_nm, is_call = lambda d: isinstance(d, ast.Name) and d.id == 'delegates', lambda d: isinstance(d, ast.Call)
	is_attr = lambda d: isinstance(d, ast.Attribute) and d.attr == 'delegates'
	is_del = lambda d: is_call(d) and (is_nm(d.func) or is_attr(d.func))
	for d in n.decorator_list:
		if not is_del(d): continue
		v = first(d.args) or getattr(first(d.keywords, lambda x:x.arg == 'to'), 'value', None)
		if v: return [_e(f"{mod}.{n.name}", f"{mod}.{ast.unparse(v)}", 'delegates', 0.85)]
	return []

def dyn_edges(src:str, module:str) -> list[dict]:
	"All dynamic dispatch edges: decorator, connect_body, registration, co_dispatch."
	tree, imp, top, all_fns, *_ = parse(src)
	if tree is None: return []
	fns, reg = [], []
	for n in ast.walk(tree):                          # one walk feeds both fns and registration
		if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)): fns.append(n)
		reg += _reg_edges(n, module, imp, all_fns)
	fns = L(fns)
	return (sum(fns.map(lambda n: _dec_edges(n, module, imp)), []) +
	        sum(fns.map(lambda n: _conn_edges(n, module)), []) +
			sum(fns.map(lambda n: _patch_edges(n, module)), []) +
			sum(fns.map(lambda n: _delegates_edges(n, module)), []) +
	        reg +
	        sum(L(tree.body).filter(lambda n: isinstance(n,ast.Assign))
	            .map(lambda n: _co_edges(n, module, top)), []))

# %% ../nbs/01_graph.ipynb #f0b09470cf1cdff7
def _srcs(sources:dict[str,str]=None, filenames:list[str]=None, root:str=None) -> dict:
	'{module: (source, file)} from either a sources dict or filenames under `root`.'
	if not filenames: return {m: (s, '') for m, s in (sources or {}).items()}
	fn = lambda p: '.'.join(Path(p).relative_to(root).with_suffix('').parts)
	return {fn(p): (Path(p).read_text(errors='replace'), str(p)) for p in filenames}

def _attr_calls(fn): return {c.func.attr for c in ast.walk(fn) if isinstance(c, ast.Call) and
	isinstance(c.func, ast.Attribute) and isinstance(c.func.value, ast.Attribute) and _root(c.func) == 'self'}

def _attr_call_hints(sources=None, filenames=None, root=None, meta=None) -> list[dict]:
	'Collect (caller, method, pkgs) for self.attr.method() calls in indexed fn bodies.'
	meta, hints = meta or {}, []
	is_mod = lambda mod, n: isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and f'{mod}.{n.name}' in meta
	for mod, (src, _) in _srcs(sources, filenames, root).items():
		tree, imp, *_ = parse(src)
		if tree is None: continue
		seen = {}
		for i, (k, v) in enumerate(imp.items()): seen[k[1:] if k.startswith('*') else v] = i
		pkgs = ','.join(p for p, _ in sorted(seen.items(), key=lambda x: x[1]))
		for fn in L(ast.walk(tree)).filter(lambda n: is_mod(mod, n)):
			for m in _attr_calls(fn): hints.append({'caller': f'{mod}.{fn.name}', 'method': m, 'pkgs': pkgs})
	return hints


# %% ../nbs/01_graph.ipynb #b455f8af20519012
@patch
def resolve_attr_calls(self: CodeGraph) -> 'CodeGraph':
	'Post-sync: resolve pending attr_call hints into edges using populated graph_nodes.'
	ex, ne, nn = {(r['caller'], r['callee']) for r in self.ge(select='caller,callee')}, [], set()
	for r in self.pa():
		if not r['pkgs']: continue
		m,p,calr = r['method'], r['pkgs'], r['caller']
		pkgs = {pkg: i for i, pkg in enumerate(p.split(','))}
		cn = L(self.gn(select='node',where=f'node like "%.{m}"')).filter(lambda r: r['node'].split('.')[0] in pkgs)
		if not cn: continue
		callee = max(cn.attrgot('node'), key=lambda n: pkgs.get(n.split('.')[0], -1))
		if (calr, callee) not in ex:
			ne.append(_e(calr, callee, 'attr_call', 0.7))
			ex.add((calr, callee))
			nn |= {calr, callee}
	if ne:
		self.ge.insert_all(ne)
		self._centrality(nn)
	return self

# %% ../nbs/01_graph.ipynb #14c0ab3d
#: ast-grep node kinds that open a Python scope, and the flavor each becomes.
_SG_KIND = {'function_definition':'function', 'class_definition':'class'}
#: `list` and `id` are defined as methods somewhere in most corpora; without this every use of the
#: builtin binds to whichever one happened to be unique.
_BUILTIN = frozenset(dir(builtins))

def _sg_scope(n) -> list:
	'Names of the defs enclosing `n`, outermost first.'
	out, p = [], n.parent()
	while p is not None:
		if p.kind() in _SG_KIND and (nm := p.field('name')): out.append(nm.text())
		p = p.parent()
	return out[::-1]

def _in_import(n) -> bool:
	'True when `n` sits in an import statement, where a name is bound rather than used.'
	p = n.parent()
	while p is not None and p.kind() in ('dotted_name','aliased_import'): p = p.parent()
	return p is not None and p.kind() in ('import_statement','import_from_statement')

def _sg_uses(root, mod:str) -> list:
	"""Return each name used by a scope as `(caller, name, on_self)`.
	Bare function references count as uses. Attribute names count only when reached through `self`."""
	out = []
	for n in root.find_all(kind='identifier'):
		p = n.parent()
		if p is None: continue
		k = p.kind()
		if k in _SG_KIND and p.field('name') == n: continue
		if _in_import(n): continue
		if k == 'attribute':
			o = p.field('object')
			if p.field('attribute') != n or o is None or o.text() != 'self': continue
			out.append(('.'.join([mod]+_sg_scope(n)), n.text(), True))
		else: out.append(('.'.join([mod]+_sg_scope(n)), n.text(), False))
	return out

def _sg_callee(f):
	'The short name a call node dispatches on: `foo` and `x.foo` both give `foo`.'
	if f.kind() == 'identifier': return f.text()
	if f.kind() == 'attribute' and (a := f.field('attribute')): return a.text()
	return None

def _sg_parse(src:str, mod:str) -> tuple:
	'Definitions and name uses in `src`, in one ast-grep pass. Returns ({node:flavor}, [(caller,name,on_self)]).'
	try: root = SgRoot(src, 'python').root()
	except Exception: return {}, []
	defs = {}
	for n in root.find_all(any=[{'kind':k} for k in _SG_KIND]):
		if not (nm := n.field('name')): continue
		sc = _sg_scope(n)
		defs['.'.join([mod]+sc+[nm.text()])] = ('method' if sc and n.kind()=='function_definition'
		                                        else _SG_KIND[n.kind()])
	return defs, _sg_uses(root, mod)

def _resolve(mod, caller, nm, on_self, defs, byname, imap):
	'Bind `nm` used in `caller`: enclosing scopes, then the module imports, then a unique global.'
	sc = caller[len(mod):].strip('.').split('.') if len(caller) > len(mod) else []
	for i in range(len(sc), -1, -1):
		if (q := '.'.join([mod]+sc[:i]+[nm])) in defs: return q
	if on_self: return None
	c = byname.get(nm)
	uniq = c[0] if c and len(c) == 1 else None
	if (q := imap.get(mod, {}).get(nm)): return _rebase(q, defs) or uniq or q
	return None if nm in _BUILTIN else uniq

def _rebase(q, defs):
	'An import says `networkx.algorithms.x`; a corpus rooted lower holds the same node as `algorithms.x`.'
	p = q.split('.')
	return first('.'.join(p[i:]) for i in range(len(p)) if '.'.join(p[i:]) in defs)

def static_edges(sources:dict[str,str]=None, filenames:list[str]=None, root:str=None) -> tuple[list[dict], dict]:
	"Static call edges via ast-grep. Provide either filenames+root or sources dict."
	assert bool(filenames) ^ bool(sources), 'Provide one of sources or filenames, but not both'
	if filenames and root is None: root = str(Path(filenames[0]).parent.parent)
	srcs = _srcs(sources, filenames, root)
	defs, calls, meta = {}, [], {}
	for mod, (src, file) in srcs.items():
		d, cs = _sg_parse(src, mod)
		defs |= d
		calls += [(mod,)+u for u in cs]
		meta |= {q: {'node':q, 'flavor':f, 'file':file, 'method':q.rsplit('.',1)[-1]} for q, f in d.items()}
	byname = groupby([q for q, f in defs.items() if f != 'method'], lambda q: q.rsplit('.',1)[-1])
	imap = {m: parse(s)[-1] or {} for m, (s, _) in srcs.items()}
	seen, edges = set(), []
	for mod, c, nm, on_self in calls:
		t = _resolve(mod, c, nm, on_self, defs, byname, imap)
		if t and t != c and (c, t) not in seen:
			seen.add((c, t)); edges.append(_e(c, t, 'static', 1.0))
	return edges, meta


# %% ../nbs/01_graph.ipynb #617b3082
def _nodes(db):
    'All nodes named in the caller and callee columns. O(E).'
    return L(r['node'] for r in db.q('''SELECT DISTINCT caller node FROM graph_edges
                                     UNION SELECT DISTINCT callee FROM graph_edges'''))

def _edge_arrays(db):
    'The edge table as (node names, src idxs, dst idxs).'
    rows = db.q('SELECT caller,callee FROM graph_edges')
    if not rows: return [], None, None
    nds = sorted({r['caller'] for r in rows} | {r['callee'] for r in rows})
    ix = {nd:i for i,nd in enumerate(nds)}
    src = np.fromiter((ix[r['caller']] for r in rows), np.int32, len(rows))
    dst = np.fromiter((ix[r['callee']] for r in rows), np.int32, len(rows))
    return nds, src, dst

def _pagerank(db, alpha=0.85, iters=50, tol=1e-6):
    'PageRank over every node'
    nds, src, dst = _edge_arrays(db)
    if not nds: return {}
    named = set(nds)
    nds = nds + [r['node'] for r in db.q('SELECT node FROM graph_nodes') if r['node'] not in named]
    n = len(nds)
    od = np.bincount(src, minlength=n)
    out = od[src]
    pr = np.full(n, 1/n)
    for _ in range(iters):
	    dm = pr[od == 0].sum()
	    nxt = (1-alpha+alpha*dm)/n + alpha*np.bincount(dst, weights=pr[src]/out, minlength=n)
	    d, pr = np.abs(nxt-pr).max(), nxt
	    if d < tol: break
    return dict(zip(nds, pr.tolist()))


# %% ../nbs/01_graph.ipynb #e5f3600ee692d5bf
#: One O(E) SQLite statement refreshes every degree.
_DEG_SQL = '''INSERT INTO graph_nodes(node,in_degree,out_degree)
SELECT node, SUM(i), SUM(o) FROM (
  SELECT callee node, 1 i, 0 o FROM graph_edges UNION ALL
  SELECT caller node, 0 i, 1 o FROM graph_edges) GROUP BY node
ON CONFLICT(node) DO UPDATE SET in_degree=excluded.in_degree, out_degree=excluded.out_degree'''

@patch
def _centrality(self: CodeGraph, nodes:set=None, force=False, tol=0.1):
	'Refresh degrees; recompute PageRank only once the edge count has moved by more than `tol`.'
	db = self.db
	db.q(_DEG_SQL)
	n = first(db.q('SELECT COUNT(*) n FROM graph_edges'))['n']
	base = self._meta('pr_edges')
	if not (force or not base or abs(n-base) > tol*base): return self
	pr = _pagerank(db)
	if pr: db.t.graph_nodes.insert_all([{'node':nd,'pagerank':round(v,12)} for nd,v in pr.items()], upsert=True, pk='node')
	self._meta('pr_edges', n)
	return self

def _uf_find(par, x):
	while par.setdefault(x,x) != x: par[x] = par[par[x]]; x = par[x]
	return x

def _uf_groups(pairs):
	'Connected components of `pairs`.'
	par = {}
	for a,b in pairs:
		ra, rb = _uf_find(par,a), _uf_find(par,b)
		if ra != rb: par[ra] = rb
	g = defaultdict(set)
	for x in par: g[_uf_find(par,x)].add(x)
	return list(g.values())

@patch
def _add_dyn(self:CodeGraph, mod_map:dict):
	"Add dynamic edges; mod_map values are src strings or Path objects."
	existing = {(r['caller'],r['callee']) for r in self.db.t.graph_edges(select='caller,callee')}
	d_edges, co, new_nodes = [], [], set()
	for mod, val in mod_map.items():
		src = Path(val).read_text(errors='replace') if isinstance(val, os.PathLike) else val
		for e in dyn_edges(src, mod):
			fr,t = e['caller'], e['callee']
			if e['kind'] == 'co_dispatch': co.append((fr,t))
			elif (fr,t) not in existing:
				d_edges.append(e)
				existing.add((fr,t))
			new_nodes |= {fr,t}
	if d_edges: self.db.t.graph_edges.insert_all(d_edges, upsert=True, pk=('caller','callee','kind'))
	if co:
		old = groupby(self.cd(), lambda r:r['group_id'], lambda r:r['node'])
		co += [(ns[0], n) for ns in old.values() for n in ns[1:]]
		self.db.q('DELETE FROM co_dispatch')
		self.cd.insert_all([{'group_id':i,'node':n} for i,g in enumerate(_uf_groups(co)) for n in g])
	return new_nodes

_cf = frozenset({'partial', 'bind', 'curry'})
def _is_cf(node):
	'True if node is a Call to a known callable factory (partial, bind, etc.).'
	if not isinstance(node, ast.Call) : return False
	if not (isinstance(node.func, ast.Name) or isinstance(node.func, ast.Attribute)): return False
	return in_(node.func.id,_cf) if isinstance(node.func, ast.Name) else in_(node.func.attr,_cf)

def _lambda_nodes(sources:dict[str,str]=None, filenames:list[str]=None, root:str=None) -> dict:
	'Extract module-level `name = lambda/partial/bind ...` nodes.'
	return {f"{mod}.{t.id}": {'node':f"{mod}.{t.id}", 'flavor':'function', 'file':file}
			for mod, (src, file) in _srcs(sources, filenames, root).items()
			for tree, *_ in [parse(src)] if tree
			for n in tree.body
			if isinstance(n, ast.Assign)
			and (isinstance(n.value, ast.Lambda) or _is_cf(n.value))
			for t in n.targets if isinstance(t, ast.Name)}

def _static_batch(kw:dict) -> tuple:
	"One batch of files or sources: (meta, edges, attr-call hints). Module-level, so a process pool can pickle it."
	s_edges, meta = static_edges(**kw)
	meta |= _lambda_nodes(**kw)
	return meta, s_edges, _attr_call_hints(**kw, meta=meta)

@patch
def _add_static(self:CodeGraph, sources:dict[str,str]=None, filenames:list[str]=None, root:str=None):
	"Static edges, lambda nodes and attr-call hints for one batch."
	return _static_batch(dict(sources=sources, filenames=filenames, root=root))

@patch
def _write_batch(self:CodeGraph, res) -> set:
	'Persist the (meta, edges, hints) triples a batch pass returned; returns the nodes touched.'
	nodes = set()
	for m, e, h in res:
		if e: self.db.t.graph_edges.insert_all(e, upsert=True, pk=('caller','callee','kind'))
		if m: self.db.t.graph_nodes.insert_all(m.values(), upsert=True, pk='node')
		if h: self.pa.insert_all(h, upsert=True, pk=('caller','method'), ignore=True)
		nodes |= set(m) | set(L(e).attrgot('caller')) | set(L(e).attrgot('callee'))
	return nodes

@patch
def from_sources(self:CodeGraph, sources:dict[str,str], chunk_size=50):
	'Build from {module_name: source_str}.'
	batches = [dict(sources=dict(c)) for c in chunked(list(sources.items()), chunk_size)]
	nodes = self._write_batch(parallel(_static_batch, batches, threadpool=False, progress=True))
	nodes |= self._add_dyn(sources)
	self._centrality(nodes)
	return self.resolve_attr_calls()


# %% ../nbs/01_graph.ipynb #3150593a339dd430
@patch
def process_files(self:CodeGraph,
	  files,  # list of .py file paths to analyse
	  root=None,  # package root; auto-detected via __init__.py walk if None
	  sz=50,  # max files per extraction pass; reduce for very large packages
) -> CodeGraph:
	'Build call-graph edges for the given source files and recompute centrality.'
	if not files: return self
	if root: files_by_root = {Path(root): list(files)}
	else: files_by_root = groupby(files, imp_root)
	nodes = set()
	for r, flist in files_by_root.items():
		batches = [dict(filenames=list(c), root=str(r)) for c in chunked(flist, sz)]
		nodes |= self._write_batch(parallel(_static_batch, batches, threadpool=False, progress=True))
	fn = lambda p: '.'.join(Path(p).relative_to(root or imp_root(p)).with_suffix('').parts)
	nodes |= self._add_dyn({fn(p): Path(p) for p in files})
	self._centrality(nodes)
	return self.resolve_attr_calls()

@patch
@fdelegates(globtastic)
def from_dir(self:CodeGraph, dir: str | Path, **kwargs) -> 'CodeGraph':
	'Build from .py files under path.'
	files = dir2files(dir, exts=['.py'], func=os.path.join, **kwargs)
	return self.process_files(files, Path(dir).parent)

@patch
@fdelegates(globtastic)
def from_pkg(self: CodeGraph, pkg: str, **kwargs) -> 'CodeGraph':
    'Build from an installed package.'
    s = spec(pkg)
    if not s: raise ValueError(f"{pkg!r} not installed")
    p = Path(s.origin).parent if s.origin else Path(s.submodule_search_locations[0])
    return self.from_dir(p, **kwargs)


# %% ../nbs/01_graph.ipynb #511f144aaca872f8
@patch
def callers(self: CodeGraph,
    n: str,           # fully-qualified node name (e.g. 'mymod.foo')
    with_kind=False   # if True, return (caller, edge_kind) tuples instead of plain names
) -> L:
    'All nodes that call `n`, optionally with edge kind.'
    fn = lambda r: (r['caller'], r['kind']) if with_kind else r['caller']
    return L(self.db.t.graph_edges(select='caller,kind', where='callee=?', where_args=[n])).map(fn)

@patch
def callees(self: CodeGraph,
    n: str,           # fully-qualified node name
    with_kind=False   # if True, return (callee, edge_kind) tuples instead of plain names
) -> L:
    'All nodes called by `n`, optionally with edge kind.'
    fn = lambda r: (r['callee'], r['kind']) if with_kind else r['callee']
    return L(self.db.t.graph_edges(select='callee,kind', where='caller=?', where_args=[n])).map(fn)

@patch
def neighbors(self: CodeGraph,
    n: str,       # fully-qualified node name
    depth: int=1  # number of hops to expand
) -> L:
    'callers + callees up to depth hops.'
    seen, frontier = set(), {n}
    for _ in range(depth):
        nxt = set()
        for node in frontier: nxt |= set(self.callers(node)) | set(self.callees(node))
        frontier = nxt - seen - {n}
        seen |= frontier
    return L(seen)

@patch
def co_dispatched(self: CodeGraph,
    node: str  # fully-qualified node name
) -> L:
    'Nodes registered in the same dispatch group as `node` (route list, handler table, etc.).'
    if not (rows := self.db.t.co_dispatch(select='group_id', where='node=?', where_args=[node])): return L()
    o=self.db.t.co_dispatch(select='node', where='group_id=? and node!=?', where_args=[rows[0]['group_id'], node])
    return L(o).attrgot('node')

@patch
def ranked(self: CodeGraph,
    k: int=10,          # number of top nodes to return
    module: str=None    # optional module prefix filter (e.g. 'fastcore.basics')
) -> L:
    'Top-k nodes by pagerank, optionally filtered to a module prefix.'
    kw = dict(where='node LIKE ?', where_args=[f"{module}.%"]) if module else {}
    return L(self.db.t.graph_nodes(select='node,pagerank', order_by='pagerank DESC', limit=k, **kw))

@patch
def _bfs(self: CodeGraph, src:str, targets:set) -> dict:
	'BFS from src; returns {tgt: L(path)} for each reachable target.'
	par, fnd, rem = {src: None}, {}, set(targets) - {src}
	fro = [src]
	_get = lambda f: self.ge(select='caller,callee', where=f'caller IN ({",".join("?" * len(f))})', where_args=f)
	while fro and rem:
		nxt = []
		for r in dict2obj(_get(fro)):
			if r.callee in par: continue
			par[r.callee] = r.caller
			path, n = [], r.callee
			while n is not None: path.append(n); n = par[n]
			fnd[r.callee] = L(reversed(path))
			rem.discard(r.callee)
			nxt.append(r.callee)
		fro = nxt
	return fnd

@patch
def short_path(self: CodeGraph,
    src: str,  # fully-qualified source node name
    tgt: str   # fully-qualified target node name
) -> L:
    'Shortest path from src to tgt via BFS. Returns L of node names or empty L.'
    if src == tgt: return L([src])
    return self._bfs(src, {tgt}).get(tgt, L())

@patch
def short_paths(self: CodeGraph,
    nodes,      # iterable of fully-qualified node names
    k: int=10   # consider only the first k nodes
) -> L:
    'Shortest paths between all pairs in top-k nodes — one BFS per source node.'
    ns = listify(nodes)[:k]
    return L(ns).map(lambda s: self._bfs(s, set(ns)-{s}).values()).concat().filter(true).sorted(key=len, reverse=True)

@patch
def edge_kinds(self: CodeGraph) -> dict:
    'Count of each edge kind in the graph (static, decorator, patch, registration, etc.).'
    return {r['kind']: r['n'] for r in self.db.q("SELECT kind, COUNT(*) n FROM graph_edges GROUP BY kind")}

@patch
def node_info(self: CodeGraph,
    node: str,        # fully-qualified node name
    with_kind=False   # include edge kind in callers/callees tuples
) -> dict:
    'Full node record: graph_nodes row merged with callers, callees, and co-dispatch peers.'
    meta = first(self.gn(xtra=dict(node=node))) or {}
    edges = dict(callers=self.callers(node,with_kind), callees=self.callees(node,with_kind))
    return meta | edges | dict(co_dispatched=self.co_dispatched(node))

# %% ../nbs/01_graph.ipynb #node_infos_batched
@patch
def node_infos(self: CodeGraph,
    nodes,            # iterable of fully-qualified node names
    with_kind=False   # include edge kind in callers/callees tuples
) -> dict:
    'Batched `node_info`: {node: graph_nodes row + callers, callees, co_dispatched}. One IN-query per relation instead of per-node.'
    nodes = list(dict.fromkeys(nodes))
    if not nodes: return {}
    ph, sel = ','.join('?'*len(nodes)), ('caller,callee,kind' if with_kind else 'caller,callee')
    gn = {r['node']: r for r in self.gn(where=f'node IN ({ph})', where_args=nodes)}
    ee = lambda r,k: (r[k], r['kind']) if with_kind else r[k]
    callees = groupby(self.ge(select=sel, where=f'caller IN ({ph})', where_args=nodes), lambda r: r['caller'], lambda r: ee(r,'callee'))
    callers = groupby(self.ge(select=sel, where=f'callee IN ({ph})', where_args=nodes), lambda r: r['callee'], lambda r: ee(r,'caller'))
    n2g = {r['node']: r['group_id'] for r in self.cd(where=f'node IN ({ph})', where_args=nodes)}
    co = {}
    if n2g:
        gp = ','.join('?'*len(set(n2g.values())))
        g2n = groupby(self.cd(where=f'group_id IN ({gp})', where_args=list(set(n2g.values()))), lambda r: r['group_id'], lambda r: r['node'])
        co = {n: L(x for x in g2n.get(g, []) if x != n) for n, g in n2g.items()}
    return {n: (gn.get(n) or {}) | dict(callers=L(callers.get(n, [])), callees=L(callees.get(n, [])), co_dispatched=co.get(n, L())) for n in nodes}

# %% ../nbs/01_graph.ipynb #5965c060
@patch
def _drop_file(self: CodeGraph, path: str):
    'Delete all graph_edges and graph_nodes belonging to this file path.'
    if not (nodes:=self.file2nodes(path)): return
    pl, nl = ','.join('?' * len(nodes)), list(nodes)
    self.db.q(f"DELETE FROM graph_edges WHERE caller IN ({pl}) OR callee IN ({pl})",nl*2)
    self.db.q(f"DELETE FROM graph_nodes WHERE node IN ({pl})", nl)
    self.db.q(f"DELETE FROM co_dispatch WHERE node IN ({pl})", nl)
    self.db.q("DELETE FROM file_index WHERE path=?", [path])

@patch
def file2nodes(self: CodeGraph, path: str) -> set:
    'Return set of node names whose file column matches path.'
    return set(L(self.db.t.graph_nodes(select='distinct node', where='file=?', where_args=[path])).attrgot('node'))

# %% ../nbs/01_graph.ipynb #96a9e1eb2d5c17f3
@patch
def _index_files(self: CodeGraph, files, sc='repo'):
	'Add or update file_index entries for these files. root is for grouping, e.g. by dir or pkg.'
	o = [dict(path=str(f), root=sc, last_analyzed_at=Path(f).stat().st_mtime) for f in files]
	self.db.t.file_index.insert_all(o, replace=True)

@patch
def _stale(self: CodeGraph, files, sc=None) -> list:
	kw = dict(where='root=?', where_args=[sc]) if sc else {}
	known = {r['path']: r['last_analyzed_at'] for r in self.db.t.file_index(**kw)}
	return [f for f in files if Path(f).exists() and known.get(str(f)) != Path(f).stat().st_mtime]

# %% ../nbs/01_graph.ipynb #92f3d9dd0997cbf6
from tqdm import tqdm

# %% ../nbs/01_graph.ipynb #27493762895c4be6
@patch(as_prop=True)
def graph(self: Kosha) -> CodeGraph:
	'code graph for this kosha instance (memoized — opens graph.db once per Kosha instance).'
	if not hasattr(self, '_graph'): self._graph = CodeGraph(self.root.joinpath('.kosha','graph.db'))
	return self._graph

@patch(as_prop=True)
def graphdb(self: Kosha):
	'Underlying graph.db database for direct queries.'
	return self.graph.db

@patch(as_prop=True)
def gn(self:Kosha):
	'graph_nodes table for direct queries.'
	return self.graph.db.t.graph_nodes

@patch(as_prop=True)
def ge(self:Kosha):
	'graph_edges table for direct queries.'
	return self.graph.db.t.graph_edges

@patch(as_prop=True)
def ni(self:Kosha):
	'Node info helper: graph_nodes row + callers, callees, co-dispatched nodes.'
	return self.graph.node_info

@patch(as_prop=True)
def neighbors(self:Kosha):
	'Neighbors helper: callers + callees up to depth hops.'
	return self.graph.neighbors

@patch(as_prop=True)
def short_path(self:Kosha):
	'Shortest path helper: shortest path between two nodes.'
	return self.graph.short_path

@patch(as_prop=True)
def short_paths(self:Kosha):
	'Shortest paths helper: shortest paths between all pairs in top-k nodes.'
	return self.graph.short_paths

# %% ../nbs/01_graph.ipynb #79635765
@patch
def public_api(self: Kosha,
               pkg: str,                         # package or module
               meta_cols: str = 'mod_name,docstring',
               limit: int = 200) -> L:
    'Return public API entries, with direct symbols ranked before nested methods.'
    get = lambda r, k: r.get('metadata', {}).get(k)
    decode = lambda r: r | dict(metadata=jl(r['metadata'])) if isinstance(r.get('metadata'), str) else r
    root, prefix = pkg.split('.')[0], f'{pkg}.%'
    pkg_ = Path(s.origin).parent.name if (s := spec(root)) else root.replace('-', '_')
    patches = L(self.ge(select='callee',where="kind='patch' AND caller LIKE ?", where_args=[prefix])).attrgot('callee')
    wh = "(json_extract(metadata, '$.public_api') = 1 AND json_extract(metadata, '$.mod_name') LIKE ?)"
    args = [prefix]
    if patches:
        ph = ','.join('?' * len(patches))
        wh += f" OR json_extract(metadata, '$.mod_name') IN ({ph})"
        args += patches
    n = max(limit * 3, 100)
    env = self.env_st(where=f"package=? AND ({wh})",where_args=[pkg_] + args,limit=n)
    repo = self.code_st(where=wh, where_args=args, limit=n)
    rows = L(env + repo).map(decode)
    rows = {get(r, 'mod_name'): r for r in rows if get(r, 'mod_name')}
    rows = L(rows.values()).sorted(key=lambda r: (get(r, 'mod_name') != pkg,get(r, 'mod_name').count('.'), get(r, 'mod_name')))
    return rows.map(lambda r: {m: get(r, m) for m in meta_cols.split(',')})[:limit]

# %% ../nbs/01_graph.ipynb #e75942176786d92c
from fastcore.all import not_
import functools

# %% ../nbs/01_graph.ipynb #3aaa2197
@patch
def status(self: Kosha, pyproject=True, depth=1) -> dict:
	'Index freshness: file/pkg/node counts and stale file count.'
	known = {r['path']: r['uploaded_at'] for r in self.code_st(select='path,uploaded_at') if r['path']}
	stale = sum(1 for p, mt in known.items() if Path(p).exists() and Path(p).stat().st_mtime != mt)
	new = sum(1 for p in dir2files(self.root,strict_skip_file_re,repo_skip_folder_re,exts=['.py']) if str(p) not in known)
	pkgs={r['name']: r['version'] for r in self.pkgs_in_env(pyproject, depth)}
	sp = filter_keys(env_pkg_versions(pyproject,depth),not_(in_(pkgs)))
	return dict(files=len(known), packages=self.pkgs.count, graph_nodes=self.gn.count, stale_files=stale, stale_pkgs=sp, new_files=new)

# %% ../nbs/01_graph.ipynb #rank_helpers_a1
# Symbol-lookup queries: namespace-qualified, leading-underscore, or containing uppercase/underscore.
_SYMBOL_QUERY_RE = re.compile(
    r"^(?:"
    r"[A-Za-z_][A-Za-z0-9_]*(?:(?:::|\\|->|\.)[A-Za-z_][A-Za-z0-9_]*)+"  # namespace-qualified
    r"|_[A-Za-z0-9_]*"  # leading underscore
    r"|[A-Za-z][A-Za-z0-9]*[A-Z_][A-Za-z0-9_]*"  # contains uppercase or underscore
    r"|[A-Z][A-Za-z0-9]*"  # starts with uppercase
    r")$")
# CamelCase/camelCase identifiers embedded in an NL query.
_EMBEDDED_SYMBOL_RE = re.compile(
    r"\b(?:"
    r"[A-Z][a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*"  # PascalCase
    r"|[a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]+"  # camelCase
    r")\b")
_CAMEL_RE = re.compile(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|[0-9]+")

_EMBEDDED_SYMBOL_BOOST_SCALE = 0.5  # embedded symbol may be incidental to the NL query
_DEFINITION_KEYWORDS = ("class","module","defmodule","def","interface","struct","enum","trait","type","func",
    "function","object","abstract class","data class","fn","fun","package","namespace","protocol","record","typedef")
_SQL_DEFINITION_KEYWORDS = ("CREATE TABLE","CREATE VIEW","CREATE PROCEDURE","CREATE FUNCTION")
_KEYWORD_PREFIX = r"(?:^|(?<=\s))(?:"
_DEFINITION_KEYWORD_BODY = "|".join(re.escape(k) for k in _DEFINITION_KEYWORDS)
_SQL_KEYWORD_BODY = "|".join(re.escape(k) for k in _SQL_DEFINITION_KEYWORDS)
_DEFINITION_BOOST_MULTIPLIER = 3.0  # additive boost for chunks defining a queried symbol
_STEM_BOOST_MULTIPLIER = 1.0        # additive boost for NL queries when file stems match query words
_FILE_COHERENCE_BOOST_FRAC = 0.2    # fraction of max_score added to a file's top chunk, scaled by aggregate score
_STOPWORDS = frozenset(
    "a an and are as at be by do does for from has have how if in is it not of on or the to was"
    " what when where which who why with".split())

_PACKAGE_BOOST = 1.5  # multiplicative boost for chunks in a soft-requested package

_TEST_FILE_RE = re.compile(
    r"(?:^|/)(?:"
    r"test_[^/]*\.py|[^/]*_test\.py|[^/]*_test\.go|[^/]*Tests?\.java|[^/]*Test\.php|[^/]*_spec\.rb|[^/]*_test\.rb"
    r"|[^/]*\.test\.[jt]sx?|[^/]*\.spec\.[jt]sx?|[^/]*Tests?\.kt|[^/]*Spec\.kt|[^/]*Tests?\.swift|[^/]*Spec\.swift"
    r"|[^/]*Tests?\.cs|test_[^/]*\.cpp|[^/]*_test\.cpp|test_[^/]*\.c|[^/]*_test\.c|[^/]*Spec\.scala|[^/]*Suite\.scala"
    r"|[^/]*Test\.scala|[^/]*_test\.dart|test_[^/]*\.dart|[^/]*_spec\.lua|[^/]*_test\.lua|test_[^/]*\.lua"
    r"|test_helpers?[^/]*\.\w+)$")
_TEST_DIR_RE = re.compile(r"(?:^|/)(?:tests?|__tests__|spec|testing)(?:/|$)")
_COMPAT_DIR_RE = re.compile(r"(?:^|/)(?:compat|_compat|legacy)(?:/|$)")
_EXAMPLES_DIR_RE = re.compile(r"(?:^|/)(?:_?examples?|docs?_src)(?:/|$)")
_TYPE_DEFS_RE = re.compile(r"\.d\.ts$")
_STRONG_PENALTY, _MODERATE_PENALTY, _MILD_PENALTY = 0.3, 0.5, 0.7
_REEXPORT_FILENAMES = frozenset({"__init__.py", "package-info.java"})
_FILE_SATURATION_THRESHOLD, _FILE_SATURATION_DECAY = 1, 0.5

def is_symbol_query(query:str) -> bool:
    'True if the query looks like a bare symbol or namespace-qualified identifier.'
    return _SYMBOL_QUERY_RE.match(query.strip()) is not None

def _split_ident(token:str) -> list:
    'Split an identifier into sub-tokens via camelCase/snake_case (lowered); keeps the whole token.'
    lower = token.lower()
    parts = [p for p in lower.split('_') if p] if '_' in token else [m.lower() for m in _CAMEL_RE.findall(token)]
    return [lower, *parts] if len(parts) >= 2 else [lower]

# ── result-dict accessors ──
def _rk_score(r): return float(r.get('_rrf_score') or r.get('_score') or 0.0)
def _rk_fpath(r): return r.get('path') or (r.get('metadata') or {}).get('path') or ''
def _rk_content(r): return r.get('content') or ''
def _rk_pkg(r): return r.get('package') or (r.get('metadata') or {}).get('package')
def _extract_symbol_name(query:str) -> str:
    'Final identifier of a possibly namespace-qualified query ("Sinatra::Base" -> "Base").'
    for sep in ('::', '\\', '->', '.'):
        if sep in query: return query.rsplit(sep, 1)[-1]
    return query.strip()

@functools.lru_cache(maxsize=256)
def _definition_pattern(symbol_name:str):
    escaped, ns_prefix = re.escape(symbol_name), r"(?:[A-Za-z_][A-Za-z0-9_]*(?:\.|::))*"
    suffix = r")\s+" + ns_prefix + escaped + r"(?:\s|[<({:\[;]|$)"
    return (re.compile(_KEYWORD_PREFIX + _DEFINITION_KEYWORD_BODY + suffix, re.MULTILINE),
            re.compile(_KEYWORD_PREFIX + _SQL_KEYWORD_BODY + suffix, re.MULTILINE | re.IGNORECASE))

def _defines_symbol(content:str, name:str) -> bool:
    general, sql = _definition_pattern(name)
    return general.search(content) is not None or sql.search(content) is not None

def _stem_matches(stem:str, name:str) -> bool:
    'True if stem matches name (exact, snake_case-normalised, or plural).'
    sn = stem.replace('_', '')
    return stem == name or sn == name or stem.rstrip('s') == name or sn.rstrip('s') == name

def _definition_tier(content:str, fpath:str, names:set, boost_unit:float) -> float:
    'Boost amount for a chunk defining one of names (0.0 if none), 1.5x when the file stem also matches.'
    if not any(_defines_symbol(content, n) for n in names): return 0.0
    stem = Path(fpath).stem.lower()
    return boost_unit * (1.5 if any(_stem_matches(stem, n.lower()) for n in names) else 1.0)

def _count_keyword_matches(keywords:set, parts:set) -> int:
    'Count query keywords matching path parts, allowing prefix overlap (min 3 chars).'
    exact = keywords & parts
    if len(exact) == len(keywords): return len(exact)
    n = len(exact)
    for kw in keywords - exact:
        for part in parts:
            shorter, longer = (kw, part) if len(kw) <= len(part) else (part, kw)
            if len(shorter) >= 3 and longer.startswith(shorter): n += 1; break
    return n

def _boost_symbol_defs(results, scores, query, mx):
    sym = _extract_symbol_name(query); names = {sym}
    if sym != query.strip(): names.add(query.strip())
    bu = mx * _DEFINITION_BOOST_MULTIPLIER
    for i, r in enumerate(results):
        if t := _definition_tier(_rk_content(r), _rk_fpath(r), names, bu): scores[i] += t

def _boost_embedded(results, scores, query, mx):
    names = set(_EMBEDDED_SYMBOL_RE.findall(query))
    if not names: return
    bu = mx * _DEFINITION_BOOST_MULTIPLIER * _EMBEDDED_SYMBOL_BOOST_SCALE
    for i, r in enumerate(results):
        if t := _definition_tier(_rk_content(r), _rk_fpath(r), names, bu): scores[i] += t

def _boost_stems(results, scores, query, mx):
    keywords = {w.lower() for w in re.findall(r"[a-zA-Z_][a-zA-Z0-9_]*", query)
                if len(w) > 2 and w.lower() not in _STOPWORDS}
    if not keywords: return
    boost = mx * _STEM_BOOST_MULTIPLIER
    for i, r in enumerate(results):
        path = Path(_rk_fpath(r)); parts = set(_split_ident(path.stem))
        if path.parent.name and path.parent.name not in ('.', '/', '..'): parts |= set(_split_ident(path.parent.name))
        n = _count_keyword_matches(keywords, parts)
        if n and (ratio := n / len(keywords)) >= 0.10: scores[i] += boost * ratio

def _apply_query_boost(results, scores, query):
    'Query-type boosts over the candidate pool (in-place): symbol-definition, or NL stem + embedded-symbol.'
    if not scores: return
    mx = max(scores)
    if is_symbol_query(query): _boost_symbol_defs(results, scores, query, mx)
    else: _boost_stems(results, scores, query, mx); _boost_embedded(results, scores, query, mx)

def _boost_multi_chunk(results, scores):
    'Promote files with multiple high-scoring chunks by boosting their top chunk (in-place).'
    if not scores or (mx := max(scores)) == 0.0: return
    fsum, best = {}, {}
    for i, r in enumerate(results):
        fp = _rk_fpath(r); fsum[fp] = fsum.get(fp, 0.0) + scores[i]
        if fp not in best or scores[i] > scores[best[fp]]: best[fp] = i
    mfs, unit = max(fsum.values()), mx * _FILE_COHERENCE_BOOST_FRAC
    for fp, i in best.items(): scores[i] += unit * fsum[fp] / mfs

def _boost_package(results, scores, soft_pkgs):
    'Multiplicatively boost chunks whose package is soft-requested (in-place). Non-filtering.'
    if not soft_pkgs: return
    sp = {p.lower() for p in soft_pkgs}
    for i, r in enumerate(results):
        if (pk := _rk_pkg(r)) and pk.lower() in sp: scores[i] *= _PACKAGE_BOOST

def _file_penalty(fpath:str) -> float:
    'Combined multiplicative penalty for test/compat/example/re-export/.d.ts paths.'
    norm = fpath.replace('\\', '/'); penalty = 1.0
    if _TEST_FILE_RE.search(norm) or _TEST_DIR_RE.search(norm): penalty *= _STRONG_PENALTY
    if Path(fpath).name in _REEXPORT_FILENAMES: penalty *= _MODERATE_PENALTY
    if _COMPAT_DIR_RE.search(norm): penalty *= _STRONG_PENALTY
    if _EXAMPLES_DIR_RE.search(norm): penalty *= _STRONG_PENALTY
    if _TYPE_DEFS_RE.search(norm): penalty *= _MILD_PENALTY
    return penalty

def _rerank_topk(results, scores, top_k, penalise_paths=True):
    'Top-k indices with path penalties + file-saturation decay. Returns [(idx, score)] highest first.'
    n = len(results)
    if n == 0: return []
    cache, pen = {}, [0.0]*n
    for i, r in enumerate(results):
        if penalise_paths:
            fp = _rk_fpath(r)
            if fp not in cache: cache[fp] = _file_penalty(fp)
            pen[i] = scores[i] * cache[fp]
        else: pen[i] = scores[i]
    ranked = sorted(range(n), key=lambda i: -pen[i])
    fsel, selected, min_sel = {}, [], float('inf')
    for i in ranked:
        ps = pen[i]
        if len(selected) >= top_k and ps <= min_sel: break
        already = fsel.get(_rk_fpath(results[i]), 0); eff = ps
        if already >= _FILE_SATURATION_THRESHOLD:
            eff *= _FILE_SATURATION_DECAY ** (already - _FILE_SATURATION_THRESHOLD + 1)
        selected.append((eff, i)); fsel[_rk_fpath(results[i])] = already + 1
        if len(selected) >= top_k: min_sel = min(s for s, _ in selected)
    selected.sort(key=lambda t: -t[0])
    return [(i, s) for s, i in selected[:top_k]]

def rank_results(results, query, soft_pkgs=None, top_k=None, penalise_paths=True) -> L:
    'Rerank result dicts: query boosts + soft-package boost + semble-style path penalties.'
    results = list(results)
    if not results or not (query and query.strip()): return L(results)[:top_k] if top_k else L(results)
    scores = [_rk_score(r) for r in results]
    if max(scores, default=0.0) == 0.0: scores = [1.0/(i+1) for i in range(len(results))]  # keep incoming order
    _apply_query_boost(results, scores, query)
    _boost_package(results, scores, soft_pkgs)
    _boost_multi_chunk(results, scores)
    ranked = _rerank_topk(results, scores, top_k or len(results), penalise_paths)
    return L(results[i] | {'_score': s} for i, s in ranked)

# %% ../nbs/01_graph.ipynb #82ba7e259675eaad
import hashlib

# %% ../nbs/01_graph.ipynb #9035c5d9
def _source_hash(src): return hashlib.blake2b(src.encode(), digest_size=16).hexdigest()
def _by_root(files, root=None):
	'{root: [files]} — one group when `root` is given, else grouped by import root.'
	return {Path(root): list(files)} if root else groupby(files, imp_root)

@patch
def _drop_file(self: CodeGraph, path: str, incoming=True):
    'Delete graph rows generated by one source file.'
    nodes = self.file2nodes(path)
    if nodes:
        pl = ','.join('?' * len(nodes)); args = list(nodes)
        where = f'caller IN ({pl})' + (f' OR callee IN ({pl})' if incoming else '')
        self.db.q(f'DELETE FROM graph_edges WHERE {where}', args * (2 if incoming else 1))
        self.db.q(f'DELETE FROM graph_nodes WHERE node IN ({pl})', args)
        self.db.q(f'DELETE FROM pending_attr_calls WHERE caller IN ({pl})', args)
        self.db.q(f'DELETE FROM co_dispatch WHERE node IN ({pl})', args)
    self.db.q('DELETE FROM file_index WHERE path=?', [path])

@patch
def _index_files(self: CodeGraph, files, sc='repo'):
    rows = []
    for f in files:
        p = Path(f); src = p.read_text(errors='replace')
        rows.append({'path': str(p), 'root': sc, 'source_hash': _source_hash(src), 'last_analyzed_at': p.stat().st_mtime})
    if rows: self.db.t.file_index.insert_all(rows, replace=True)

@patch
def _stale(self: CodeGraph, files, sc=None, force=False):
    kw = dict(where='root=?', where_args=[sc]) if sc else {}
    known = {r['path']: r.get('source_hash') for r in self.db.t.file_index(**kw)}
    out = []
    for f in files:
        p = Path(f)
        if not p.exists(): continue
        src = p.read_text(errors='replace')
        if force or known.get(str(p)) != _source_hash(src): out.append(f)
    return out

@patch
def _fast_process_files(self: CodeGraph, files, root=None, full=False):
	'Re-extract the changed files in one pass.'
	if not files: return self
	old = set().union(*(self.file2nodes(str(f)) for f in files))
	for f in files: self._drop_file(str(f), incoming=False)
	if full: self.process_files(files, root=root)
	else:
		groups = _by_root(files, root)
		self._write_batch([_static_batch(dict(filenames=[str(f) for f in fl], root=str(r)))
		                   for r, fl in groups.items()])
		self._add_dyn({'.'.join(Path(f).relative_to(r).with_suffix('').parts): Path(f)
		               for r, fl in groups.items() for f in fl})
		self.resolve_attr_calls()
	gone = old - set().union(*(self.file2nodes(str(f)) for f in files))
	if gone:
		pl = ','.join('?' * len(gone))
		self.db.q(f'DELETE FROM graph_edges WHERE callee IN ({pl})', list(gone))
	return self

@patch
def sync_dir(self: CodeGraph, dir: str | Path, force=False, mode='fast', root=None) -> 'CodeGraph':
    'Incremental directory sync; unchanged source hashes are skipped.'
    if not dir: return self
    files = dir2files(dir, exts=['.py'], func=os.path.join)
    known = set(L(self.db.t.file_index(select='distinct path', where='root=?', where_args=[str(dir)])).attrgot('path'))
    removed = known - set(files)
    for f in removed: self._drop_file(f)
    changed = self._stale(files, str(dir), force)
    if changed: self._fast_process_files(changed, str(root) if root else None, full=mode == 'full'); self._index_files(changed, str(dir))
    self._graph_changed = getattr(self, '_graph_changed', False) or bool(removed or changed)
    return self

@patch
def sync_pkgs(self: CodeGraph, pkgs: list[str], force=False, mode='fast') -> 'CodeGraph':
    'Incrementally sync installed packages by source hash.'
    for pkg in tqdm(pkgs or [], desc='loading code graph for packages', unit='pkg'):
        s = spec(pkg)
        if not s: continue
        p = Path(s.origin).parent if s.origin else Path(s.submodule_search_locations[0])
        self.sync_dir(p, force=force, mode=mode, root=p.parent)
    return self

@patch
def sync(self: CodeGraph, dir=None, pkgs=None, force=False, mode='fast', metrics=True) -> 'CodeGraph':
    'Incremental graph sync; mode="full" fans out over processes, metrics=False defers PageRank.'
    self._graph_changed = force
    if force: self.pa.delete_where()
    if dir: self.sync_dir(dir, force=force, mode=mode)
    if pkgs: self.sync_pkgs(pkgs, force=force, mode=mode)
    if metrics and self._graph_changed: self._centrality()
    return self

@patch
def recompute_metrics(self: CodeGraph) -> 'CodeGraph':
    'Recompute PageRank and degree metrics once after graph updates.'
    return self._centrality(force=True)

@patch
def resolve_attr_calls(self: CodeGraph) -> 'CodeGraph':
    'Resolve pending attribute calls using the indexed method column.'
    existing = {(r['caller'], r['callee']) for r in self.ge(select='caller,callee')}
    new_edges = []
    for r in self.pa():
        if not r['pkgs']: continue
        pkgs = {pkg: i for i, pkg in enumerate(r['pkgs'].split(','))}
        candidates = [x for x in self.gn(where='method=?', where_args=[r['method']]) if x['node'].split('.')[0] in pkgs]
        if not candidates: continue
        callee = max((x['node'] for x in candidates), key=lambda n: pkgs.get(n.split('.')[0], -1))
        if (r['caller'], callee) not in existing:
            new_edges.append(_e(r['caller'], callee, 'attr_call', 0.7)); existing.add((r['caller'], callee))
    if new_edges: self.ge.insert_all(new_edges, upsert=True, pk=('caller','callee','kind'))
    return self


# %% ../nbs/01_graph.ipynb #6f57bfb4
@patch
def sync(self: Kosha,
         pkgs=None, # list of package names to sync (e.g. ['httpx', 'fastcore']); if None, sync every stale env package
         dir=None, # directory to sync; if None, sync all of root
         verbose=True, # print progress messages
		 in_parallel=True, # preserve the existing public default; pass False for serialized SQLite graph sync
		 graph_mode='fast', # use 'full' to extract graph batches in worker processes
		 graph_metrics=True, # preserve PageRank refresh; pass False to defer it
         force=False, # ignore file mtimes and reprocess everything, graph included
         repo=True, # index the repo
         env=True, # index env packages; False is how you say "this repo only", whatever `pkgs` holds
         graph=True, # build the call graph — incrementally, unless `force`
         sync_graph=None, # deprecated: the old name for `graph`
         pyproject=True, # if True, auto-detect env packages from pyproject.toml; if False, use pkgs argument as-is
         depth=1, # depth for pyproject env package detection; ignored if pyproject=False
         embed=True, # whether to embed
         pkg_parallel=False, # ingest env packages concurrently; requires Kosha(busy_timeout=...)
         chunk=5_000 # rows per write transaction when pkg_parallel=True
 ) -> 'Kosha':
	'Sync the code store, the env store and the code graph'
	if sync_graph is not None: graph = sync_graph
	if verbose: print(f'Syncing dir={dir or self.root}, repo={repo}, env={env}, graph={graph}, force={force}')
	dir = dir or self.root
	pkgs = (listify(pkgs) or list(self.status(pyproject,depth).get('stale_pkgs', {}))) if env else []
	pkgs = L(pkgs).map(_pkg_name).unique()
	ts = [bind(self.update_repo, dir, verbose=verbose, force=force, embed=embed) if repo else (lambda: None),
		  bind(self.update_pkgs, pkgs, verbose=verbose, force=force, embed=embed, parallel=pkg_parallel, chunk=chunk)
		      if pkgs else (lambda: None),
		  bind(self.graph.sync, dir=dir if repo else None, pkgs=pkgs, force=force, mode=graph_mode, metrics=graph_metrics) if graph else (lambda: None)]
	if in_parallel: return parallel(lambda f: f(), ts, threadpool=True, progress=True)
	else: return L(ts).map(lambda f: f())

@patch
def context(self: Kosha,
			q: str,               # query with optional key:value filters
			limit: int = 50,
			repo: bool = True,
			env: bool = True,
			graph: bool = True,
            boost: bool = True,
			compact: bool = False, # return slim dicts (mod_name, signature, docstring, lineno) instead of full chunks
            columns:str='content,metadata',
            sys_wide=True,
            rerank: bool = False,     # reorder the boosted top-k with a flashrank cross-encoder
            rerank_model: str = None, # flashrank model name (None -> fast default)
			**kw                  # forwarded to env_context / repo_context
) -> L:
	'Fan-out semantic search: parse filters, run repo + env searches, merge with chained RRF, then rerank.'
	# self.update_repo()
	def _tag(res,pref): return L(res).map(lambda r:r|dict(_source=pref,_src_id=f'{pref}:{r.get("rowid",id(r))}'))
	# Embed the query exactly once and pass via emb_q= so repo/env don't each re-embed.
	from kosha.core import parseq
	raw, fs = parseq(q)
	if pkg:= fs.get('package', []): repo = False
	exec_ls = [lambda: self.repo_context(q, emb_q=raw, limit=limit*2, columns=columns, **kw) if repo else noop(),
	           lambda: self.env_context(q, emb_q=raw, limit=limit*2, columns=columns, sys_wide=sys_wide, **kw) if env else noop()]
	fn = lambda f: f()
	rr, er = parallel(fn, exec_ls, threadpool=True)
	res = L(rrf_all(L(_tag(rr,'repo'), _tag(er,'env')), limit=limit*2, id_key='_src_id'))
	if not res: return L()
	soft_pkgs = set(pkg) if pkg else set(raw.split()) & set(self.pkgs2consider(sys_wide))
	ranked = rank_results(res, raw, soft_pkgs=soft_pkgs, top_k=limit) if boost else res
	if rerank: ranked = L(rerank_hits(raw, list(ranked), rerank_model, limit))
	if graph:
		em = self.graph.node_infos([r['metadata']['mod_name'] for r in ranked])
		ranked = L(ranked.map(lambda r: r | em.get(r['metadata']['mod_name'], {})))
	if compact:
		meta = lambda r: filter_keys(r['metadata'],in_(['mod_name','docstring','lineno','path']))
		return ranked.map(lambda r:meta(r)|dict(sig=(r['content'].splitlines()[0])))
	return dict2obj(ranked)

# %% ../nbs/01_graph.ipynb #pkg_deps_task_context_c3d4
def is_sys_pkg(pkg:str) -> bool:
	'Return True if pkg is a system-wide package (e.g. in site-packages), False if likely user code.'
	from importlib.metadata import distribution as dist, PackageNotFoundError
	try: return bool(dist(pkg))
	except PackageNotFoundError: return False

@patch
def dep_stack(self:Kosha, seeds:list=None, depth:int=1, no_sys_pkg=True, allow:list=None) -> list:
	'BFS over pkg_deps, ordered by coupling strength.'
	seen, frontier, layers = set(seeds), set(seeds), [list(seeds)]
	fn=lambda p: p['tgt'] not in seen and (not no_sys_pkg or is_sys_pkg(p['tgt'])) and (not allow or p['tgt'] in allow)
	for _ in range(depth):
		if not frontier: break
		_pl = ','.join('?'*len(frontier))
		kw = dict(where=f'from_pkg IN ({_pl})', where_args=list(frontier))
		nxt = set(L(self.env_pd(select='to_pkg tgt,n_modules n',**kw)).filter(fn).attrgot('tgt'))
		if not nxt: break
		layers+=[nxt]
		seen |= nxt
		frontier = nxt
	return layers

@patch
def top_nodes(self:Kosha, pkg:str, k:int=5) -> L:
	'Top-k public API nodes for pkg ranked by pagerank in the code graph.'
	mods = self.public_api(pkg, meta_cols='mod_name').attrgot('mod_name')
	if not mods: return L()
	pl = ','.join('?'*len(mods))
	o = self.gn(select='node,pagerank', order_by='pagerank DESC', limit=k, where=f'node IN ({pl})', where_args=mods)
	return L(o).attrgot('node')

@patch
def api_call_paths(self:Kosha,
	from_pkg: str,  # package whose public API is the call source
	to_pkg: str,    # package whose public API is the call target
	k: int = 15     # top-k API nodes per package to consider
) -> dict:
	'Shortest call-graph paths from from_pkg public API nodes to to_pkg public API nodes.'
	f,a = self.top_nodes(from_pkg, k), self.top_nodes(to_pkg, k)
	paths = {}
	for fp in f: paths = paths | self.graph._bfs(fp, set(a))
	return filter_keys(paths, in_(a))

# %% ../nbs/01_graph.ipynb #8d82814f
@patch
@fdelegates(Kosha.context)
def where_to_add(self: Kosha, description: str, limit: int = 5, **kwargs) -> L:
	'Likely insertion points for new code: file + line from top context results + co_dispatched peers.'
	results = self.context(description, limit=limit, **kwargs)
	je = lambda v: f"json_extract(metadata,'$.mod_name')={v!r}"
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if 'metadata' in r else r
	locfn = lambda m: dict(path=m.get('path'),lineno=m.get('lineno'),end_lineno=m.get('end_lineno') or m.get('lineno'))
	def _loc(n):
		r = L(self.code_st(select='metadata', where=je(n), limit=1)).map(fn)
		return dict(node=n) | locfn(r[0]['metadata']) if r else {}
	out, seen = [], set()
	for r in results:
		mod = r['metadata'].get('mod_name', '')
		if not mod or mod in seen: continue
		seen.add(mod)
		loc = _loc(mod)
		if not loc or not loc['path']: continue
		co = list(r.get('co_dispatched', []))
		peer_ends = [p['end_lineno'] for c in co if (p := _loc(c)) and p['path'] == loc['path'] and p['end_lineno']]
		insert_after = max([loc['end_lineno'] or 0] + peer_ends, default=loc['lineno'])
		out+=[dict(node=mod,path=loc['path'],insert_after=insert_after,co_dispatched=co,pagerank=r.get('pagerank',0))]
	return L(out)
