"""CodeGraph: call-graph layer for kosha, backed by graph.db. Augments semantic search with structural traversal."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_graph.ipynb.

# %% auto #0
__all__ = ['CodeGraph', 'dyn_edges', 'static_edges', 'is_sys_pkg']

# %% ../nbs/01_graph.ipynb #ff995efe
import ast, re, os
from json import loads as jl
from collections import defaultdict
from litesearch import *
from fastcore.all import (Path, L, patch, parallel_async, tuplify, first, fdelegates, globtastic, bind, true, dict2obj,
                          listify, filter_keys, in_, filter_values)
from .core import arun, Kosha, embedder, parse, has_init, env_pkg_versions
from pyan.analyzer import CallGraphVisitor
from pyan.anutils import Scope, ExecuteInInnerScope

# %% ../nbs/01_graph.ipynb #eb2b59dfd7c9a091
try:
	# Bug 1 fix: auto-register missing nested lambda scopes
	def _safe_enter(self):
		o = self.analyzer
		o.name_stack.append(self.scopename)
		try: inner_ns = o.get_node_of_current_namespace().get_name()
		except Exception: inner_ns = '.'.join(o.name_stack)
		if inner_ns not in o.scopes: o.scopes[inner_ns] = Scope.from_names(self.scopename, [])
		o.scope_stack.append(o.scopes[inner_ns])
		o.context_stack.append(self.scopename)
		self.inner_ns = inner_ns
		return self
	ExecuteInInnerScope.__enter__ = _safe_enter

	# Bug 2 fix: guard None namespace in postprocessing
	_ANON = {'<listcomp>','<setcomp>','<dictcomp>','<genexpr>','<lambda>'}
	_orig_gp = CallGraphVisitor.get_parent_node
	def _safe_gp(self, n):
		if n.namespace is None: return None
		return _orig_gp(self, n)
	def _safe_collapse(self):
		for name in list(self.nodes):
			if name.partition('.')[0] not in _ANON: continue
			for n in self.nodes[name]:
				if n.namespace is None: continue
				pn = self.get_parent_node(n)
				if pn is None: continue
				for n2 in self.uses_edges.get(n, []): self.add_uses_edge(pn, n2)
				n.defined = False
	CallGraphVisitor.get_parent_node = _safe_gp
	CallGraphVisitor.collapse_inner  = _safe_collapse
except ImportError: pass

# %% ../nbs/01_graph.ipynb #af482cb1
class CodeGraph:
	'''Call graph builder and query engine. Uses pyan3 for static analysis and custom AST parsing for dynamic edges.
	Stores everything in a SQLite database.
	'''
	def __init__(self, path: str | Path = ':memory:'):
		self.path = path
		self.db = database(path)
		ge, gn, cd, fi = self.db.t.graph_edges, self.db.t.graph_nodes, self.db.t.co_dispatch, self.db.t.file_index
		ge.create(id=int, caller=str, callee=str, kind=str, confidence=float, if_not_exists=True, pk='id')
		ge.create_index(['caller'], if_not_exists=True)
		ge.create_index(['callee'], if_not_exists=True)
		ge.create_index(['kind'], if_not_exists=True)
		gn.create(node=str, flavor=str, file=str, pagerank=float, in_degree=int,
				  out_degree=int, if_not_exists=True, pk='node')
		cd.create(group_id=int, node=str, if_not_exists=True)
		fi.create(path=str, root=str, last_analyzed_at=float, if_not_exists=True, pk='path')
		fi.create_index(['root'], if_not_exists=True)
		self.ge, self.gn, self.cd, self.fi = ge, gn, cd, fi

	def nuke(self): [t.drop() for t in (self.ge, self.gn, self.cd, self.fi)]

# %% ../nbs/01_graph.ipynb #82f10dfa
_reg_re = re.compile(
    r'^(add|register|include|on|connect|mount|sub(scribe)?|listen|use|route|handle|hook|attach|bind|plug|get|post|'
    r'put|delete|patch|head|options|before|after|middleware)(_\w+)?$', re.IGNORECASE)
_conn = {'connect', 'setup', 'register', 'init_app', 'create_app', 'mount','configure','bootstrap','install','activate'}
_web_pkg = {'fasthtml', 'flask', 'fastapi', 'starlette', 'django', 'aiohttp','sanic','tornado','litestar','blacksheep'}

# %% ../nbs/01_graph.ipynb #578eec3e302e059c
def _root(n):
	while isinstance(n, ast.Attribute): n = n.value
	return n.id if isinstance(n, ast.Name) else None

def _conf(root, verb, imp):
	pkg = imp.get(root) or next((v for k,v in imp.items() if k.startswith('*')), None)
	return 0.95 if pkg in _web_pkg else 0.75 if _reg_re.match(verb or '') else 0.5

def _e(caller, callee, kind, conf): return {'caller':caller,'callee':callee,'kind':kind,'confidence':conf}

def _dec_edges(n, mod, imp):
	fn = f"{mod}.{n.name}"
	return [_e(f"{mod}.{r}", fn, 'decorator', _conf(r, inner.attr, imp))
	        for dec in n.decorator_list
	        for inner in [dec.func if isinstance(dec,ast.Call) else dec]
	        if isinstance(inner,ast.Attribute) and (r := _root(inner))]

def _conn_edges(n, mod):
	if n.name not in _conn or not n.args.args: return []
	param, fn = n.args.args[0].arg, f'{mod}.{n.name}'
	return [_e(fn, f'{mod}.{a.id}', 'connect_body', 0.9)
	        for child in ast.walk(n)
	        if isinstance(child,ast.Call) and isinstance(child.func,ast.Attribute)
	        and _root(child.func) == param
	        for a in child.args if isinstance(a,ast.Name)]

def _reg_edges(n, mod, imp, all_fns):
	if not (isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and _reg_re.match(n.func.attr)): return []
	root = _root(n.func) or 'unknown'
	return [_e(f"{mod}.{root}", f"{mod}.{a.id}", 'registration', _conf(root, n.func.attr, imp))
	        for a in n.args if isinstance(a,ast.Name) and a.id in all_fns]

def _co_edges(n, mod, top_fns):
	if not (isinstance(n,ast.Assign) and isinstance(getattr(n,'parent',None), ast.Module)): return []
	val = n.value
	grp = ([v.id for v in val.values if isinstance(v,ast.Name) and v.id in top_fns] if isinstance(val,ast.Dict) else
	       [e.id for e in val.elts if isinstance(e,ast.Name) and e.id in top_fns]
	       if isinstance(val,(ast.List,ast.Tuple)) else [])
	return [_e(f"{mod}.{a}",f"{mod}.{b}",'co_dispatch',0.8) for i,a in enumerate(grp) for b in grp[i+1:]]

def _patch_edges(n, mod):
	'fastcore @patch: @patch def fn(self:Class) → Class gains fn as method.'
	if not any(('patch' in ast.unparse(d)) for d in n.decorator_list): return []
	if not ((args := n.args.args) and (ann:=args[0].annotation)): return []
	tgts = ([ast.unparse(ann.left), ast.unparse(ann.right)]
			   if isinstance(ann, ast.BinOp) and isinstance(ann.op, ast.BitOr)
			   else [ast.unparse(ann)])
	return [_e(f"{mod}.{t}", f"{mod}.{n.name}", 'patch', 0.9) for t in tgts]

def _delegates_edges(n, mod):
	'fastcore @delegates(target): fn wraps target\'s signature — structural dependency.'
	is_nm, is_call = lambda d: isinstance(d, ast.Name) and d.id == 'delegates', lambda d: isinstance(d, ast.Call)
	is_attr = lambda d: isinstance(d, ast.Attribute) and d.attr == 'delegates'
	is_del = lambda d: is_call(d) and (is_nm(d.func) or is_attr(d.func))
	for d in n.decorator_list:
		if not (is_del(d) and (v:=d.args[0] if d.args else first(d.keywords, lambda kw:kw.arg == 'to'))): continue
		return [_e(f"{mod}.{n.name}", f"{mod}.{ast.unparse(v)}", 'delegates', 0.85)]
	return []

def dyn_edges(src:str, module:str) -> list[dict]:
	"All dynamic dispatch edges: decorator, connect_body, registration, co_dispatch."
	tree, imp, top, all_fns, *_ = parse(src)
	if tree is None: return []
	fns = L(ast.walk(tree)).filter(lambda n: isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)))
	return (sum(fns.map(lambda n: _dec_edges(n, module, imp)), []) +
	        sum(fns.map(lambda n: _conn_edges(n, module)), []) +
			sum(fns.map(lambda n: _patch_edges(n, module)), []) +
			sum(fns.map(lambda n: _delegates_edges(n, module)), []) +
	        sum(L(ast.walk(tree)).map(lambda n: _reg_edges(n, module, imp, all_fns)), []) +
	        sum(L(tree.body).filter(lambda n: isinstance(n,ast.Assign))
	            .map(lambda n: _co_edges(n, module, top)), []))

# %% ../nbs/01_graph.ipynb #14c0ab3d
def _build_imap(sources=None, filenames=None, root=None):
	'Build {module: {local_name: qualified_name}} for resolving None-namespace callee nodes.'
	if filenames:
		fn = lambda p: '.'.join(Path(p).relative_to(root).with_suffix('').parts)
		srcs = {fn(p): Path(p).read_text(errors='replace') for p in filenames}
	else: srcs = sources or {}
	return L(set(srcs)).map_dict(lambda m: parse(srcs[m])[-1] or {})

def static_edges(sources:dict[str,str]=None, filenames:list[str]=None, root:str=None) -> tuple[list[dict], dict]:
	"Static call edges via pyan3. Provide either filenames+root or sources dict."
	assert bool(filenames) ^ bool(sources), 'Provide one of sources or filenames, but not both'
	if filenames and root is None: root = str(Path(filenames[0]).parent.parent)
	try:
		from pyan.analyzer import CallGraphVisitor
		if filenames: v = CallGraphVisitor(filenames, root=root)
		else: v = CallGraphVisitor.from_sources(tuplify((s,m) for m,s in sources.items()))
		v.postprocess()
		imap = _build_imap(sources=sources, filenames=filenames, root=root)
		def _callee(c, t):
			if t.namespace and t.namespace != '*': return f'{t.namespace}.{t.name}'
			if t.namespace is None:
				parts = c.namespace.split('.')
				for i in range(len(parts), 0, -1):
					if (m:='.'.join(parts[:i])) in imap and t.name in imap[m]: return imap[m][t.name]
			return None
		return ([_e(f'{c.namespace}.{c.name}', cl, 'static', 1.0)
				 for c,ts in v.uses_edges.items() if c.namespace and c.namespace != '*'
				 for t in ts if '^^^' not in (t.name or '') and (cl := _callee(c,t))],
				{f"{n.namespace}.{n.name}":
					 {'node':f"{n.namespace}.{n.name}",
					  'flavor':str(n.flavor).split('.')[-1].lower(), 'file':n.filename or ''}
				 for nlist in v.nodes.values() for n in nlist if hasattr(n,'name') and n.namespace})
	except Exception as ex: print(f"pyan3 static analysis failed: {ex}"); return [], {}

# %% ../nbs/01_graph.ipynb #617b3082
def _nodes(db):
    'All node connectors buy caller and callee columns. O(E).'
    return L(r['node'] for r in db.q('''SELECT DISTINCT caller node FROM graph_edges
                                     UNION SELECT DISTINCT callee FROM graph_edges'''))

def _pagerank(db, nodes:set=None, alpha=0.85, iters=50, tol=1e-6):
    'Iterative PageRank with precomputed adjacency — O(E + N·iters).'
    nodes = nodes or _nodes(db)
    if not nodes: return {}
    n = len(nodes)
    pr = {nd: 1/n for nd in nodes}
    out,in_e = defaultdict(int), defaultdict(list)
    for r in db.t.graph_edges(select='caller,callee'):
	    out[r['caller']] += 1
	    in_e[r['callee']].append(r['caller'])
    for _ in range(iters):
	    new = {nd:(1-alpha)/n + alpha*sum(pr.get(c, 0)/(out[c] or 1) for c in in_e[nd]) for nd in nodes}
	    if max(abs(new[nd]-pr[nd]) for nd in nodes) < tol: break
	    pr = new
    return pr

# %% ../nbs/01_graph.ipynb #e5f3600ee692d5bf
@patch
def _centrality(self: CodeGraph, nodes:set=None):
	db = self.db
	pr = _pagerank(db, nodes)
	in_d  = {r['nd']:r['n'] for r in db.q('SELECT callee nd,COUNT(*) n FROM graph_edges GROUP BY callee')}
	out_d = {r['nd']:r['n'] for r in db.q('SELECT caller nd,COUNT(*) n FROM graph_edges GROUP BY caller')}
	db.t.graph_nodes.insert_all([{'node':nd, 'pagerank':round(pr.get(nd,0),5), 'in_degree':in_d.get(nd,0),
	                              'out_degree':out_d.get(nd,0)} for nd in set(pr)], upsert=True, pk='node')
	return self

@patch
def _add_dyn(self:CodeGraph, mod_map:dict):
	"Add dynamic edges; mod_map values are src strings or Path objects."
	existing = {(r['caller'],r['callee']) for r in self.db.t.graph_edges(select='caller,callee')}
	d_edges, groups, new_nodes = [], [], set()
	for mod, val in mod_map.items():
		src = Path(val).read_text(errors='replace') if isinstance(val, os.PathLike) else val
		for e in dyn_edges(src, mod):
			fr,t = e['caller'], e['callee']
			if e['kind'] == 'co_dispatch':
				for grp in groups:
					if {fr,t} & grp: grp |= {fr,t}; break
				else: groups.append({fr,t})
			elif (fr,t) not in existing:
				d_edges.append(e)
				existing.add((fr,t))
			new_nodes |= {fr,t}
	if d_edges: self.db.t.graph_edges.insert_all(d_edges)
	if groups:
		base = first(self.db.q('SELECT COALESCE(MAX(group_id)+1,0) n FROM co_dispatch'))['n']
		self.db.t.co_dispatch.insert_all([{'group_id':base+i,'node':nd} for i,grp in enumerate(groups) for nd in grp])
	return new_nodes

def _lambda_nodes(sources:dict[str,str]=None, filenames:list[str]=None, root:str=None) -> dict:
	'Extract module-level `name = lambda ...` nodes; same signature as static_edges.'
	if filenames:
		fn = lambda p: '.'.join(Path(p).relative_to(root).with_suffix('').parts)
		sources = {fn(p): (Path(p).read_text(errors='replace'), str(p)) for p in filenames}
	else: sources = {mod: (src, '') for mod, src in (sources or {}).items()}
	return {f"{mod}.{t.id}": {'node':f"{mod}.{t.id}", 'flavor':'function', 'file':file}
			for mod, (src, file) in sources.items()
			for tree, *_ in [parse(src)] if tree
			for n in tree.body
			if isinstance(n, ast.Assign) and isinstance(n.value, ast.Lambda)
			for t in n.targets if isinstance(t, ast.Name)}

@patch
def _add_static(self:CodeGraph, sources:dict[str,str]=None, filenames:list[str]=None, root:str=None):
	"Add static edges from sources dict. Uses pyan3 for full-corpus analysis."
	s_edges, meta = static_edges(sources=sources, filenames=filenames, root=root)
	meta |= _lambda_nodes(sources=sources, filenames=filenames, root=root)
	if s_edges: self.db.t.graph_edges.insert_all(s_edges)
	if meta: self.db.t.graph_nodes.insert_all(meta.values(), upsert=True, pk='node')
	return set(meta) | set(L(s_edges).attrgot('caller')) | set(L(s_edges).attrgot('callee'))

@patch
def from_sources(self:CodeGraph, sources:dict[str,str]):
	'Build from {module_name: source_str}.'
	return self._centrality(self._add_static(sources=sources) | self._add_dyn(sources))

# %% ../nbs/01_graph.ipynb #3150593a339dd430
@patch
def process_files(self:CodeGraph,
    files,     # list of .py file paths to analyse
    root=None  # package root; auto-detected via __init__.py walk if None
):
	'Build static + dynamic call-graph edges for the given source files and recompute centrality.'
	if root is None or not files: root = files[0] if files else '.'
	pkg_dir = Path(str(files[0])).parent
	while has_init(pkg_dir): pkg_dir = pkg_dir.parent
	root = str(pkg_dir)
	nodes = self._add_static(filenames=files, root=root)
	fn = lambda p: '.'.join(Path(p).relative_to(root).with_suffix('').parts)
	nodes |= self._add_dyn({fn(p): Path(p) for p in files})
	return self._centrality(nodes)

@patch
@fdelegates(globtastic)
def from_dir(self:CodeGraph, dir: str | Path, **kwargs) -> 'CodeGraph':
	'Build from .py files under path — pyan reads files directly.'
	files = dir2files(dir, exts=['.py'], func=os.path.join, **kwargs)
	return self.process_files(files, Path(dir).parent)

@patch
def from_file(self: CodeGraph, path:str|Path) -> 'CodeGraph':
	'Build from a single .py file. Module name derived from filename.'
	p = Path(path).resolve()
	pkg_root, parts = p.parent, [p.with_suffix('').name]
	while has_init(pkg_root):
		parts.insert(0, pkg_root.name)
		pkg_root = pkg_root.parent
	return self._centrality(self._add_static(filenames=[str(p)], root=pkg_root) | self._add_dyn({'.'.join(parts): p}))

@patch
@fdelegates(globtastic)
def from_pkg(self: CodeGraph, pkg: str, **kwargs) -> 'CodeGraph':
    'Build from an installed package. Uses pyan3 on the package source files.'
    s = spec(pkg)
    if not s: raise ValueError(f"{pkg!r} not installed")
    p = Path(s.origin).parent if s.origin else Path(s.submodule_search_locations[0])
    return self.from_dir(p, **kwargs)

# %% ../nbs/01_graph.ipynb #511f144aaca872f8
@patch
def callers(self: CodeGraph,
    n: str,           # fully-qualified node name (e.g. 'mymod.foo')
    with_kind=False   # if True, return (caller, edge_kind) tuples instead of plain names
) -> L:
    'All nodes that call `n`, optionally with edge kind.'
    fn = lambda r: (r['caller'], r['kind']) if with_kind else r['caller']
    return L(self.db.t.graph_edges(select='caller,kind', where='callee=?', where_args=[n])).map(fn)

@patch
def callees(self: CodeGraph,
    n: str,           # fully-qualified node name
    with_kind=False   # if True, return (callee, edge_kind) tuples instead of plain names
) -> L:
    'All nodes called by `n`, optionally with edge kind.'
    fn = lambda r: (r['callee'], r['kind']) if with_kind else r['callee']
    return L(self.db.t.graph_edges(select='callee,kind', where='caller=?', where_args=[n])).map(fn)

@patch
def neighbors(self: CodeGraph,
    n: str,       # fully-qualified node name
    depth: int=1  # number of hops to expand
) -> L:
    'callers + callees up to depth hops.'
    seen, frontier = set(), {n}
    for _ in range(depth):
        nxt = set()
        for node in frontier: nxt |= set(self.callers(node)) | set(self.callees(node))
        frontier = nxt - seen - {n}
        seen |= frontier
    return L(seen)

@patch
def co_dispatched(self: CodeGraph,
    node: str  # fully-qualified node name
) -> L:
    'Nodes registered in the same dispatch group as `node` (route list, handler table, etc.).'
    if not (rows := self.db.t.co_dispatch(select='group_id', where='node=?', where_args=[node])): return L()
    o=self.db.t.co_dispatch(select='node', where='group_id=? and node!=?', where_args=[rows[0]['group_id'], node])
    return L(o).attrgot('node')

@patch
def ranked(self: CodeGraph,
    k: int=10,          # number of top nodes to return
    module: str=None    # optional module prefix filter (e.g. 'fastcore.basics')
) -> L:
    'Top-k nodes by pagerank, optionally filtered to a module prefix.'
    kw = dict(where='node LIKE ?', where_args=[f"{module}.%"]) if module else {}
    return L(self.db.t.graph_nodes(select='node,pagerank', order_by='pagerank DESC', limit=k, **kw))

@patch
def _bfs(self: CodeGraph, src:str, targets:set) -> dict:
	'BFS from src; returns {tgt: L(path)} for each reachable target.'
	par, fnd, rem = {src: None}, {}, set(targets) - {src}
	fro = [src]
	_get = lambda f: self.ge(select='caller,callee', where=f'caller IN ({",".join("?" * len(f))})', where_args=f)
	while fro and rem:
		nxt = []
		for r in dict2obj(_get(fro)):
			if r.callee in par: continue
			par[r.callee] = r.caller
			if r.callee in fnd: continue
			path, n = [], r.callee
			while n is not None: path.append(n); n = par[n]
			fnd[r.callee] = L(reversed(path))
			rem.discard(r.callee)
			nxt.append(r.callee)
		fro = nxt
	return fnd

@patch
def short_path(self: CodeGraph,
    src: str,  # fully-qualified source node name
    tgt: str   # fully-qualified target node name
) -> L:
    'Shortest path from src to tgt via BFS. Returns L of node names or empty L.'
    if src == tgt: return L([src])
    return self._bfs(src, {tgt}).get(tgt, L())

@patch
def short_paths(self: CodeGraph,
    nodes,      # iterable of fully-qualified node names
    k: int=10   # consider only the first k nodes
) -> L:
    'Shortest paths between all pairs in top-k nodes — one BFS per source node.'
    ns = listify(nodes)[:k]
    return L(ns).map(lambda s: self._bfs(s, set(ns)-{s}).values()).concat().filter(true).sorted(key=len, reverse=True)

@patch
def edge_kinds(self: CodeGraph) -> dict:
    'Count of each edge kind in the graph (static, decorator, patch, registration, etc.).'
    return {r['kind']: r['n'] for r in self.db.q("SELECT kind, COUNT(*) n FROM graph_edges GROUP BY kind")}

@patch
def node_info(self: CodeGraph,
    node: str,        # fully-qualified node name
    with_kind=False   # include edge kind in callers/callees tuples
) -> dict:
    'Full node record: graph_nodes row merged with callers, callees, and co-dispatch peers.'
    meta = first(self.gn(xtra=dict(node=node))) or {}
    edges = dict(callers=self.callers(node,with_kind), callees=self.callees(node,with_kind))
    return meta | edges | dict(co_dispatched=self.co_dispatched(node))

# %% ../nbs/01_graph.ipynb #5965c060
@patch
def _drop_file(self: CodeGraph, path: str):
    'Delete all graph_edges and graph_nodes belonging to this file path.'
    if not (nodes:=self.file2nodes(path)): return
    pl, nl = ','.join('?' * len(nodes)), list(nodes)
    self.db.q(f"DELETE FROM graph_edges WHERE caller IN ({pl}) OR callee IN ({pl})",nl*2)
    self.db.q(f"DELETE FROM graph_nodes WHERE node IN ({pl})", nl)
    self.db.q(f"DELETE FROM co_dispatch WHERE node IN ({pl})", nl)
    self.db.q("DELETE FROM file_index WHERE path=?", [path])

@patch
def file2nodes(self: CodeGraph, path: str) -> set:
    'Return set of node names whose file column matches path.'
    return set(L(self.db.t.graph_nodes(select='distinct node', where='file=?', where_args=[path])).attrgot('node'))

# %% ../nbs/01_graph.ipynb #96a9e1eb2d5c17f3
@patch
def _index_files(self: CodeGraph, files, sc='repo'):
	'Add or update file_index entries for these files. root is for grouping, e.g. by dir or pkg.'
	o = [dict(path=str(f), root=sc, last_analyzed_at=Path(f).stat().st_mtime) for f in files]
	self.db.t.file_index.insert_all(o, replace=True)

@patch
def _stale(self: CodeGraph, files, sc=None) -> list:
	kw = dict(where='root=?', where_args=[sc]) if sc else {}
	known = {r['path']: r['last_analyzed_at'] for r in self.db.t.file_index(**kw)}
	return [f for f in files if Path(f).exists() and known.get(str(f)) != Path(f).stat().st_mtime]

# %% ../nbs/01_graph.ipynb #cd099cdc
@patch
def sync_dir(self: CodeGraph, dir: str | Path, force=False) -> 'CodeGraph':
	'Incremental sync for a directory: drop missing files, update changed files, add new files.'
	if not dir: print('no action. dir empty'); return self
	files = dir2files(dir, exts=['.py'], func=os.path.join)
	known=set(L(self.db.t.file_index(select='distinct path', where='root=?', where_args=[str(dir)])).attrgot('path'))
	for f in known - set(files): self._drop_file(f)
	fs = files if force else self._stale(files, str(dir))
	if fs: self.process_files(fs, str(dir)) and self._index_files(fs, str(dir))
	return self

@patch
def sync_pkgs(self: CodeGraph, pkgs: list[str]) -> 'CodeGraph':
	'Incremental sync for packages: drop missing files, update changed files, add new files.'
	if not pkgs: print('no action. pkgs empty'); return self

	arun(parallel_async(self.from_pkg, pkgs))
	return self

@patch
def sync(self: CodeGraph, dir=None, pkgs=None, force=False) -> 'CodeGraph':
	'Incremental sync: from_dir per dir, from_pkg per pkg; manage file_index.'
	self.sync_dir(dir, force) and self.sync_pkgs(pkgs)
	return self

# %% ../nbs/01_graph.ipynb #27493762895c4be6
@patch(as_prop=True)
def graph(self: Kosha) -> CodeGraph:
	'code graph for this kosha instance'
	return CodeGraph(self.root.joinpath('.kosha','graph.db'))

@patch(as_prop=True)
def graphdb(self: Kosha):
	'Underlying graph.db database for direct queries.'
	return self.graph.db

@patch(as_prop=True)
def gn(self:Kosha):
	'graph_nodes table for direct queries.'
	return self.graph.db.t.graph_nodes

@patch(as_prop=True)
def ge(self:Kosha):
	'graph_edges table for direct queries.'
	return self.graph.db.t.graph_edges

@patch(as_prop=True)
def ni(self:Kosha):
	'Node info helper: graph_nodes row + callers, callees, co-dispatched nodes.'
	return self.graph.node_info

@patch(as_prop=True)
def neighbors(self:Kosha):
	'Neighbors helper: callers + callees up to depth hops.'
	return self.graph.neighbors

@patch(as_prop=True)
def short_path(self:Kosha):
	'Shortest path helper: shortest path between two nodes.'
	return self.graph.short_path

@patch(as_prop=True)
def short_paths(self:Kosha):
	'Shortest paths helper: shortest paths between all pairs in top-k nodes.'
	return self.graph.short_paths

# %% ../nbs/01_graph.ipynb #public_api_graph_aware_a1b2
@patch
def public_api(self: Kosha,
               pkg: str,         # package or module to index (e.g. 'kosha', 'litesearch.data')
               meta_cols:str='mod_name,docstring', # metadata keys to extract
               limit: int = 200  # max names to return
               ) -> L:
	'Return public API: all public_api=1 entries + @patch-derived methods from the call graph from env and repo stores.'
	fn = lambda r: r | dict(metadata=jl(r['metadata'])) if isinstance(r.get('metadata'), str) else r
	_get= lambda r, k: r.get('metadata', {}).get(k)
	je = lambda o,e='=',v='': 'json_extract(metadata,"$.%s") %s %s'%(o,e,v)
	p = pkg.split('.')[0]
	pkg_ = Path(s.origin).parent.name if (s:=spec(p)) else p.replace('-', '_')
	patch_ = self.ge(select='callee',where="kind='patch' AND caller LIKE ?",where_args=[f'{pkg}.%'])
	wh, kw = je('public_api',v='1'), dict(where_args=None)
	if patch_:
		_ph = '(%s)' % ','.join('?' * len(patch_))
		wh += ' OR ' + je('mod_name','in',_ph)
		kw = dict(where_args=L(patch_).attrgot('callee'))
	_dir_cond = je('dir','like',repr(pkg_))
	er = self.env_st(where=f"package={pkg_!r} AND ({wh})",limit=limit,**kw)
	rr = self.code_st(where=f'{_dir_cond} AND {wh}',limit=limit,**kw)
	return L(er+rr).map(fn).map(lambda r: {m: _get(r,m) for m in meta_cols.split(',')})[:limit]


# %% ../nbs/01_graph.ipynb #6f57bfb4
@patch
def sync(self: Kosha,
         pkgs=None, # list of package names to sync (e.g. ['httpx', 'fastcore']); if None, sync all env packages
         dir=None, # directory to sync; if None, sync all of root
         emb=embedder, # optional embedder for graph sync; if None, skip embedding and graph sync steps
         verbose=True, # print progress messages
         in_parallel=False, # run repo, env, and graph sync in parallel
         force=False, # ignore file mtimes and reprocess all files
         pyproject=True, # if True, auto-detect env packages from pyproject.toml; if False, use pkgs argument as-is
         depth=1, # depth for pyproject env package detection; ignored if pyproject=False
         embed=True # whether to embed
 ) -> 'Kosha':
	'Sync code store, env store, and code graph. Runs in a daemon thread by default.'
	dir, pkgs = dir or self.root, pkgs or set(env_pkg_versions(pyproject,depth))
	g_pkgs = set(pkgs) if force else set(pkgs) - set(L(self.pkgs(select='distinct name')).attrgot('name'))
	ts = [bind(self.update_repo, dir, efn=emb, verbose=verbose, force=force, embed=embed),
		  bind(self.update_pkgs, pkgs, efn=emb, verbose=verbose, force=force, embed=embed),
		  bind(self.graph.sync, dir=dir, pkgs=g_pkgs, force=force)]
	if in_parallel: return arun(parallel_async(lambda f: f(), ts))
	else: return L(ts).map(lambda f: f())

@patch
def context(self: Kosha,
			q: str,               # query with optional key:value filters
			limit: int = 50,
			repo: bool = True,
			env: bool = True,
			graph: bool = True,
            columns:str='content,metadata',
            sys_wide=True,
			**kw                  # forwarded to env_context / repo_context
) -> L:
	'Fan-out semantic search: parse filters, run repo + env searches, merge with chained RRF.'
	def _tag(res, pref): return L(res).map(lambda r: r | dict(_src_id=f'{pref}:{r.get("rowid", id(r))}'))
	items = []
	if repo: items.append(('repo', bind(self.repo_context, q, limit=limit*2, columns=columns, **kw)))
	if env: items.append(('env', bind(self.env_context, q, limit=limit*2, columns=columns,sys_wide=sys_wide, **kw)))
	results = L(arun(parallel_async(lambda f: (f[0],f[1]()), items)))
	results = results.map(lambda r: _tag(r[1], r[0]))
	rrf = bind(rrf_merge, limit=limit*2, id_key='_src_id')
	res = L(L(results[1:]).reduce(lambda m,rs: rrf(m,rs), results[0]))
	if not graph: return res[:limit]
	return dict2obj(res.map(lambda r : r | self.ni(r['metadata']['mod_name'])))[:limit]

# %% ../nbs/01_graph.ipynb #pkg_deps_task_context_c3d4
def is_sys_pkg(pkg:str) -> bool:
	'Return True if pkg is a system-wide package (e.g. in site-packages), False if likely user code.'
	from importlib.metadata import distribution as dist, PackageNotFoundError
	try: return bool(dist(pkg))
	except PackageNotFoundError: return False

@patch
def dep_stack(self:Kosha, seeds:list=None, depth:int=1, no_sys_pkg=True, allow:list=None) -> list:
	'BFS over pkg_deps, ordered by coupling strength.'
	seen, frontier, layers = set(seeds), set(seeds), [list(seeds)]
	fn=lambda p: p['tgt'] not in seen and (not no_sys_pkg or is_sys_pkg(p['tgt'])) and (not allow or p['tgt'] in allow)
	for _ in range(depth):
		if not frontier: break
		_pl = ','.join('?'*len(frontier))
		kw = dict(where=f'from_pkg IN ({_pl})', where_args=list(frontier))
		nxt = set(L(self.env_pd(select='to_pkg tgt,n_modules n',**kw)).filter(fn).attrgot('tgt'))
		if not nxt: break
		layers+=[nxt]
		seen |= nxt
		frontier = nxt
	return layers

@patch
def top_nodes(self:Kosha, pkg:str, k:int=5) -> L:
	'Top-k public API nodes for pkg ranked by pagerank in the code graph.'
	mods = self.public_api(pkg, meta_cols='mod_name').attrgot('mod_name')
	if not mods: return L()
	pl = ','.join('?'*len(mods))
	o = self.gn(select='node,pagerank', order_by='pagerank DESC', limit=k, where=f'node IN ({pl})', where_args=mods)
	return L(o).attrgot('node')

@patch
def api_call_paths(self:Kosha,
	from_pkg: str,  # package whose public API is the call source
	to_pkg: str,    # package whose public API is the call target
	k: int = 15     # top-k API nodes per package to consider
) -> dict:
	'Shortest call-graph paths from from_pkg public API nodes to to_pkg public API nodes.'
	f,a = self.top_nodes(from_pkg, k), self.top_nodes(to_pkg, k)
	paths = {}
	for fp in f: paths = paths | self.graph._bfs(fp, set(a))
	return filter_keys(paths, in_(a))


# %% ../nbs/01_graph.ipynb #graph-diff-a1b2
@patch
def graph_diff(self: Kosha, snapshot_path: str = None) -> dict:
    'Delta since last snapshot: new/removed nodes+edges, top PageRank shifts. Call after sync().'
    import json as _json
    sp = Path(snapshot_path or (Path(self.root) / '.kosha' / 'graph_snapshot.json'))
    cur_nodes = {r['node']: r['pagerank'] for r in self.graph.gn()}
    cur_edges = {(r['caller'], r['callee'], r['kind']) for r in self.graph.ge()}
    if not sp.exists():
        sp.write_text(_json.dumps({'nodes': cur_nodes, 'edges': [list(e) for e in cur_edges]}))
        return dict(new_nodes=[], removed_nodes=[], new_edges=[], removed_edges=[], pagerank_shifts=[])
    prev = _json.loads(sp.read_text())
    prev_nodes, prev_edges = prev['nodes'], {tuple(e) for e in prev['edges']}
    new_nodes     = [n for n in cur_nodes  if n not in prev_nodes]
    removed_nodes = [n for n in prev_nodes if n not in cur_nodes]
    new_edges     = [list(e) for e in cur_edges  if e not in prev_edges]
    removed_edges = [list(e) for e in prev_edges if e not in cur_edges]
    shifts = sorted(
        [(n, prev_nodes[n], cur_nodes[n]) for n in cur_nodes
         if n in prev_nodes and abs(cur_nodes[n] - prev_nodes[n]) > 1e-5],
        key=lambda x: abs(x[2]-x[1]), reverse=True)
    sp.write_text(_json.dumps({'nodes': cur_nodes, 'edges': [list(e) for e in cur_edges]}))
    return dict(new_nodes=new_nodes, removed_nodes=removed_nodes,
                new_edges=new_edges, removed_edges=removed_edges, pagerank_shifts=shifts[:20])

# %% ../nbs/01_graph.ipynb #surprising-conn-c3d4
@patch
def surprising_connections(self: Kosha, top_n: int = 10, use_embeddings: bool = True) -> L:
    'Unexpected cross-module call relationships ranked by structural + embedding-distance surprise.'
    import numpy as np
    nodes = {r['node']: r for r in self.graph.gn()}

    def _emb(name):
        je = f"json_extract(metadata,'$.mod_name')={name!r}"
        r = (first(self.code_st(select='embedding', where=je)) or
             first(self.env_st(select='embedding', where=je)))
        if r and r.get('embedding'): return np.frombuffer(r['embedding'], dtype=np.float32)

    def _cos_dist(a, b):
        if a is None or b is None: return None
        n = np.linalg.norm(a) * np.linalg.norm(b)
        return float(1 - np.dot(a, b) / n) if n > 0 else 1.0

    cross_edges = [(e['caller'], e['callee'], e['kind'], e['confidence'])
                   for e in self.graph.ge()
                   if e['caller'].split('.')[0] != e['callee'].split('.')[0]
                   or e['confidence'] < 0.9]
    involved = {n for e in cross_edges for n in (e[0], e[1])}
    embs = {n: _emb(n) for n in involved} if use_embeddings else {}
    scored = []
    for caller, callee, kind, conf in cross_edges:
        cross = caller.split('.')[0] != callee.split('.')[0]
        tgt = nodes.get(callee)
        score = (1 - conf) + (0.4 if cross else 0) + (min(tgt['pagerank']*200, 0.5) if tgt else 0)
        emb_dist = _cos_dist(embs.get(caller), embs.get(callee)) if use_embeddings else None
        if emb_dist: score += emb_dist * 0.5
        scored.append((score, dict(caller=caller, callee=callee, kind=kind, confidence=conf,
                                   cross_module=cross,
                                   embedding_distance=round(emb_dist, 3) if emb_dist is not None else None,
                                   surprise_score=round(score, 3))))
    scored.sort(key=lambda x: x[0], reverse=True)
    return L(s[1] for s in scored[:top_n])
