"""Move a top-level definition to another file and repoint every import that named it, on top of the index that already knows where the symbol lives.

Docs: https://vedicreader.github.io/kosha/refactor.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_refactor.ipynb.

# %% ../nbs/02_refactor.ipynb #0e050985
from __future__ import annotations
import ast, builtins, re, textwrap
from dataclasses import dataclass
from functools import partial
from itertools import accumulate
from fastcore.all import Path, first
from .core import imp_root

# %% auto #0
__all__ = ['FileEdit', 'replace_plan', 'top_symbols', 'module_of', 'extract', 'inline', 'move_plan']

# %% ../nbs/02_refactor.ipynb #55fcf9b3
_BUILTINS = frozenset(dir(builtins))

@dataclass
class FileEdit:
    "One file's whole text before and after, so a plan can be shown, applied, and undone."
    path: str
    before: str
    after: str
    edits: int
    def dict(self): return dict(path=self.path, before=self.before, after=self.after, edits=self.edits)

def _read(path):
    "A file's text, or None when it does not exist."
    p = Path(path)
    return p.read_text(encoding='utf-8', errors='replace') if p.is_file() else None

# %% ../nbs/02_refactor.ipynb #099cb28e
def _pattern(query, regex=False, case=False, word=False):
    if not query: raise ValueError('find text is empty')
    text = query if regex else re.escape(query)
    if word: text = r'\b' + text + r'\b'
    try: return re.compile(text, 0 if case else re.I)
    except re.error as e: raise ValueError(f'invalid regular expression: {e}') from e

def replace_plan(paths, query, replacement, regex=False, case=False, word=False, read=_read):
    "Changed files for one literal or regular-expression replacement, and the paths left unread."
    pat = _pattern(str(query), bool(regex), bool(case), bool(word))
    repl = str(replacement) if regex else str(replacement).replace('\\', '\\\\')
    rows, skipped = [], []
    for path in paths:
        if Path(path).suffix.lower() == '.ipynb': skipped.append(str(path)); continue
        try: before = read(path)
        except Exception: before = None
        if before is None or '�' in before: skipped.append(str(path)); continue
        try: after, n = pat.subn(repl, before)
        except re.error as e: raise ValueError(f'invalid replacement: {e}') from e
        if n: rows.append(FileEdit(str(path), before, after, n))
    return rows, skipped

# %% ../nbs/02_refactor.ipynb #02659f6d
def _starts(source):
    "Character offset at which each line begins, plus the end of the text."
    return list(accumulate(map(len, source.splitlines(True)), initial=0))

def _at(source, starts, node):
    "A node's (start, end) character offsets. `col_offset` counts utf-8 bytes, not characters."
    def one(lineno, col):
        begin = starts[lineno - 1]
        return begin + len(source[begin:starts[lineno]].encode()[:col].decode('utf-8', 'ignore'))
    return one(node.lineno, node.col_offset), one(node.end_lineno, node.end_col_offset)

def _parse(path, source):
    try: return ast.parse(source)
    except SyntaxError as e: raise ValueError(f'{Path(path).name} does not parse: {e.msg} (line {e.lineno})') from e

# %% ../nbs/02_refactor.ipynb #af9d6bf9
def _span(source, starts, node):
    "What a definition owns: the comments above it, its decorators, and the blank lines below."
    lines = source.splitlines()
    top = min([d.lineno for d in getattr(node, 'decorator_list', [])] + [node.lineno])
    while top > 1 and lines[top - 2].lstrip().startswith('#'): top -= 1
    end = node.end_lineno
    while end < len(lines) and not lines[end].strip(): end += 1
    return starts[top - 1], starts[end]

def top_symbols(source):
    "Top-level functions and classes, each with the character span it owns."
    tree, starts = ast.parse(source), _starts(source)
    kind = lambda n: 'class' if isinstance(n, ast.ClassDef) else 'function'
    return [dict(name=n.name, kind=kind(n), line=n.lineno, **dict(zip(('start', 'end'), _span(source, starts, n))))
            for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]

# %% ../nbs/02_refactor.ipynb #6cc9113c
def module_of(path):
    "Dotted module name for a file, from the top of its `__init__.py` chain."
    p = Path(path)
    parts = p.relative_to(imp_root(p)).with_suffix('').parts
    return '.'.join(parts[:-1] if p.stem == '__init__' else parts)

# %% ../nbs/02_refactor.ipynb #ebcfaf5b
def _bound(tree):
    "Every name a module binds at its top level, mapped to the statement that binds it."
    out = {}
    for n in tree.body:
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)): out[n.name] = n
        elif isinstance(n, (ast.Import, ast.ImportFrom)):
            for a in n.names: out[(a.asname or a.name).split('.')[0]] = n
        elif isinstance(n, ast.Assign):
            for t in n.targets:
                for x in ast.walk(t):
                    if isinstance(x, ast.Name): out[x.id] = n
        elif isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name): out[n.target.id] = n
    return out

def _free(nodes, exclude=_BUILTINS):
    "Names the nodes read without binding, which is what has to reach them wherever they go."
    load, store = set(), set()
    for node in nodes:
        for n in ast.walk(node):
            if isinstance(n, ast.Name): (load if isinstance(n.ctx, ast.Load) else store).add(n.id)
            elif isinstance(n, ast.arg): store.add(n.arg)
            elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)): store.add(n.name)
            elif isinstance(n, ast.alias): store.add((n.asname or n.name).split('.')[0])
            elif isinstance(n, ast.ExceptHandler) and n.name: store.add(n.name)
            elif isinstance(n, ast.Global): store.update(n.names)
    return load - store - set(exclude)

# %% ../nbs/02_refactor.ipynb #15ebedb5
def _name(name):
    if not str(name).isidentifier(): raise ValueError('name must be a valid Python identifier')
    return str(name)

def _line(source, pos): return source.count('\n', 0, pos), source.rfind('\n', 0, pos) + 1

def _indent(source, pos):
    _, start = _line(source, pos)
    return re.match(r'[ \t]*', source[start:]).group()

def _expr(text):
    try: return ast.parse(text, mode='eval').body
    except SyntaxError as e: raise ValueError('select one complete Python expression') from e

def _writes(nodes):
    "Every name the selection binds."
    return {n.id for node in nodes for n in ast.walk(node)
            if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Store)}

def _reads(text):
    """Every name the text loads, so a name still wanted afterwards can be told from a dead one.

    The tail of a file is the middle of a block and rarely parses. The identifier fallback errs
    towards handing a value back, which is untidy rather than broken."""
    for candidate in (text, textwrap.dedent(text)):
        try: tree = ast.parse(candidate)
        except SyntaxError: continue
        return {n.id for n in ast.walk(tree) if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)}
    return set(re.findall(r'\b[A-Za-z_][A-Za-z0-9_]*\b', text))

# %% ../nbs/02_refactor.ipynb #a82d5674
#: Where a statement reads before it binds. `ast.walk` is breadth-first, so it would see the target
#: of `total = total + 1` before the value and call the name already bound.
_EVAL_ORDER = {ast.Assign: ('value', 'targets'), ast.AugAssign: ('value', 'target'),
               ast.AnnAssign: ('value', 'target'), ast.For: ('iter', 'target'),
               ast.AsyncFor: ('iter', 'target'), ast.comprehension: ('iter', 'target'),
               ast.withitem: ('context_expr', 'optional_vars')}

def _children(value):
    if isinstance(value, list): return [x for x in value if isinstance(x, ast.AST)]
    return [value] if isinstance(value, ast.AST) else []

def _reads_before_writes(nodes):
    """Names the selection reads before it binds them: those have to arrive as parameters.

    A name both read and bound, as in `total = total + n`, is a parameter as well as a result.
    Subtracting the bound names from the read ones would miss it."""
    bound, params = set(), []
    def visit(node):
        if isinstance(node, ast.Name):
            if isinstance(node.ctx, ast.Load):
                if node.id not in bound and node.id not in params: params.append(node.id)
            else: bound.add(node.id)
            return
        if (order := _EVAL_ORDER.get(type(node))) is not None:
            for field in order:
                for child in _children(getattr(node, field, None)): visit(child)
            for name, value in ast.iter_fields(node):
                if name in order: continue
                for child in _children(value): visit(child)
            return
        for child in ast.iter_child_nodes(node): visit(child)
    for node in nodes: visit(node)
    return sorted(params)

# %% ../nbs/02_refactor.ipynb #5a247fcc
def _enclosing_method(source, pos):
    "The method `pos` sits in and the indent its siblings use, or a reason there is none."
    tree, starts = ast.parse(source), _starts(source)
    for cls in [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]:
        for fn in [n for n in cls.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]:
            begin, stop = _at(source, starts, fn)
            if begin <= pos <= stop: return fn, ' ' * fn.col_offset
    raise ValueError("extract a method from inside one of a class's own methods")

def _offset_after(source, node):
    "Where a sibling of `node` goes: the end of the statement it follows."
    starts = _starts(source)
    for fn in [n for n in ast.walk(ast.parse(source))
               if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == node.name]:
        return _at(source, starts, fn)[1]
    return len(source)

# %% ../nbs/02_refactor.ipynb #0551774f
def extract(path, source, start, end, kind, name):
    "One safe single-file extraction; unsupported selections fail rather than guess."
    start, end, name = int(start), int(end), _name(name)
    if not 0 <= start < end <= len(source): raise ValueError('select code before extracting')
    text, indent = source[start:end], _indent(source, start)
    if kind in {'variable', 'constant'}:
        node = _expr(text)
        if kind == 'constant':
            try: ast.literal_eval(node)
            except Exception as e: raise ValueError('constants must be literal values') from e
            name = name.upper()
            if not re.fullmatch(r'[A-Z_][A-Z0-9_]*', name): raise ValueError('constant names use UPPER_CASE')
            if indent: raise ValueError('extract constants from module scope')
            tree = ast.parse(source); at = 0
            if tree.body and isinstance(tree.body[0], ast.Expr) and isinstance(tree.body[0].value, ast.Constant): at = tree.body[0].end_lineno
            while at < len(source.splitlines()) and source.splitlines()[at].startswith(('import ', 'from ')): at += 1
            point = sum(len(x) + 1 for x in source.splitlines()[:at])
            after = source[:point] + f'{name} = {text}\n' + source[point:start] + name + source[end:]
        else:
            line, line_start = _line(source, start)
            after = source[:line_start] + f'{indent}{name} = {text}\n' + source[line_start:start] + name + source[end:]
        return FileEdit(path, source, after, 1)
    if kind not in {'function', 'method'}: raise ValueError('unknown extraction')
    if source[_line(source, start)[1]:start].strip() or source[end:source.find('\n', end) if source.find('\n', end) >= 0 else len(source)].strip():
        raise ValueError('functions require complete statement lines')
    # the selection carries its own indentation, and `ast` will not parse an indented block
    block = textwrap.dedent(text)
    try: selected = ast.parse(block).body
    except SyntaxError as e: raise ValueError(f'select whole statements to extract ({e.msg})') from e
    if not selected: raise ValueError('select statements')
    if any(isinstance(n, (ast.Return, ast.Yield, ast.YieldFrom)) for node in selected for n in ast.walk(node)):
        raise ValueError('a selection that returns or yields cannot be lifted into its own function')
    params, stores = _reads_before_writes(selected), _writes(selected)
    params = [p for p in params if p not in _BUILTINS]
    returns = sorted(n for n in stores if n in _reads(source[end:]))
    body = ''.join(indent + '    ' + line if line.strip() else line for line in block.splitlines(True))
    if not body.endswith('\n'): body += '\n'   # a selection can end mid-line; a body cannot
    if returns: body += f'{indent}    return {", ".join(returns)}\n'
    args = list(params)
    if kind != 'method':
        call, head = f'{name}({", ".join(args)})', ', '.join(args)
        if returns: call = f'{", ".join(returns)} = {call}'
        definition = f'{indent}def {name}({head}):\n{body}'
        return FileEdit(path, source, source[:start] + definition + '\n' + indent + call + '\n' + source[end:], 1)
    # a method has to be a sibling of the one it came out of: nested inside it, `self.name` is
    # not an attribute of anything
    args = [p for p in args if p != 'self']
    call = f'self.{name}({", ".join(args)})'
    if returns: call = f'{", ".join(returns)} = {call}'
    holder, member = _enclosing_method(source, start)
    body = textwrap.indent(textwrap.dedent(body), member + '    ')
    definition = f'\n\n{member}def {name}(self{", " if args else ""}{", ".join(args)}):\n{body.rstrip()}\n'
    after = source[:start] + indent + call + '\n' + source[end:]
    at = _offset_after(after, holder)
    return FileEdit(path, source, after[:at] + definition + after[at:], 1)

# %% ../nbs/02_refactor.ipynb #56badaec
_ATOMIC = (ast.Name, ast.Constant, ast.Attribute, ast.Subscript, ast.Call,
           ast.List, ast.Dict, ast.Set, ast.ListComp, ast.DictComp, ast.SetComp, ast.JoinedStr)

def _binding(tree, name):
    "The one plain `name = value` statement that defines `name`, or a reason there isn't one."
    if any(name in n.names for n in ast.walk(tree) if isinstance(n, (ast.Global, ast.Nonlocal))):
        raise ValueError(f'{name} is declared global or nonlocal')
    stores = [n for n in ast.walk(tree) if isinstance(n, ast.Name) and n.id == name
              and isinstance(n.ctx, (ast.Store, ast.Del))]
    plain = [n for n in ast.walk(tree) if isinstance(n, ast.Assign) and len(n.targets) == 1
             and isinstance(n.targets[0], ast.Name) and n.targets[0].id == name]
    if len(plain) != 1 or len(stores) != 1:
        raise ValueError(f'inline needs {name} assigned exactly once, as a plain `{name} = value`')
    return plain[0]

def inline(path, source, pos):
    "Replace a variable's uses with its value and delete the assignment."
    pos = int(pos)
    if not 0 <= pos <= len(source): raise ValueError('put the cursor on a variable first')
    tree, starts = ast.parse(source), _starts(source)
    at = partial(_at, source, starts)
    spans = {n: at(n) for n in ast.walk(tree) if isinstance(n, ast.Name)}
    here = first(n for n, (a, b) in spans.items() if a <= pos <= b)
    if here is None: raise ValueError('put the cursor on a variable first')
    assign = _binding(tree, here.id)
    astart, aend = at(assign)
    lstart, lend = starts[assign.lineno - 1], starts[assign.end_lineno]
    if source[lstart:astart].strip() or source[aend:lend].strip():
        raise ValueError('inline needs the assignment on lines of its own')
    value = source[slice(*at(assign.value))]
    if not isinstance(assign.value, _ATOMIC): value = f'({value})'
    uses = [span for n, span in spans.items() if n.id == here.id and isinstance(n.ctx, ast.Load)]
    if not uses: raise ValueError(f'{here.id} is never read, so there is nothing to inline')
    if any(a < aend for a, _ in uses): raise ValueError(f'{here.id} is read before it is assigned')
    after = source
    for a, b in sorted(uses, reverse=True): after = after[:a] + value + after[b:]
    return FileEdit(path, source, after[:lstart] + after[lend:], len(uses))

# %% ../nbs/02_refactor.ipynb #78ecec60
def _absolute(node, here):
    "The absolute module an `ImportFrom` names, resolving `level` against the module holding it."
    if not node.level: return node.module or ''
    return '.'.join([*here.split('.')[:-node.level], *([node.module] if node.module else [])])

def _stmt(target, here, names):
    "A `from ... import` reaching `target` from `here`, relative where a shared package allows one."
    tp, hp = target.split('.'), here.split('.')[:-1]
    n = 0
    while n < len(tp) - 1 and n < len(hp) and tp[n] == hp[n]: n += 1
    dots = '.' * (len(hp) - n + 1) if n else ''
    return f"from {dots}{'.'.join(tp[n:])} import {', '.join(names)}"

def _spec(alias): return f'{alias.name} as {alias.asname}' if alias.asname else alias.name
def _from(node, aliases): return f"from {'.' * node.level}{node.module or ''} import {', '.join(_spec(a) for a in aliases)}"

# %% ../nbs/02_refactor.ipynb #caeb2415
def _is_all(n):
    return (isinstance(n, ast.Assign) and len(n.targets) == 1
            and isinstance(n.targets[0], ast.Name) and n.targets[0].id == '__all__')

def _import_point(tree, starts):
    "Where a new import goes: below the docstring, and below the header of imports and `__all__`."
    body, at, i = tree.body, 0, 0
    if body and isinstance(body[0], ast.Expr) and isinstance(getattr(body[0].value, 'value', None), str):
        at, i = starts[body[0].end_lineno], 1
    while i < len(body) and (isinstance(body[i], (ast.Import, ast.ImportFrom)) or _is_all(body[i])):
        at, i = starts[body[i].end_lineno], i + 1
    return at

def _froms(tree, here, module):
    "Every top-level `from module import ...` in the file, with the specs each one carries."
    return [(n, {_spec(a) for a in n.names}) for n in tree.body
            if isinstance(n, ast.ImportFrom) and _absolute(n, here) == module]

def _add_imports(text, tree, starts, here, froms, plains):
    "Edits folding `froms` into whatever import block the file already has, plus the plain imports."
    edits, add = [], []
    plain_texts = {f'import {_spec(a)}' for n in ast.walk(tree) if isinstance(n, ast.Import) for a in n.names}
    for module, specs in sorted(froms.items()):
        if module == here: continue
        block = _froms(tree, here, module)
        node, have = first((n, h) for n, h in block if specs & h) or first(block) or (None, set())
        want = sorted(have | set(specs))
        if want == sorted(have): continue
        if node is not None: edits.append((*_at(text, starts, node), _stmt(module, here, want)))
        else: add.append(_stmt(module, here, sorted(specs)))
    add += [p for p in sorted(plains) if p not in plain_texts]
    if add:
        at = _import_point(tree, starts)
        gap = '' if text[at:at + 1] in ('\n', '') else '\n'   # an import block never runs straight into a definition
        edits.append((at, at, ''.join(s + '\n' for s in add) + gap))
    return edits

def _apply(text, edits):
    for a, b, new in sorted(edits, reverse=True): text = text[:a] + new + text[b:]
    return text

# %% ../nbs/02_refactor.ipynb #6e680cc3
def _all_edit(text, starts, tree, add=(), drop=()):
    "An edit rewriting a module's `__all__`, or None when it has none this can read."
    node = first(n for n in tree.body if _is_all(n))
    if node is None or not isinstance(node.value, (ast.List, ast.Tuple)): return None
    cur = [e.value for e in node.value.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    if len(cur) != len(node.value.elts): return None
    new = [x for x in cur if x not in set(drop)] + [x for x in add if x not in cur]
    if new == cur: return None
    return (*_at(text, starts, node.value), '[' + ', '.join(repr(x) for x in new) + ']')

def _carry(froms, plains, node, name, here):
    "Record the import that gave `name` to the source file, so the destination gains it too."
    alias = first(a for a in node.names if (a.asname or a.name).split('.')[0] == name)
    if isinstance(node, ast.ImportFrom): froms.setdefault(_absolute(node, here), set()).add(_spec(alias))
    else: plains.add(f'import {_spec(alias)}')

# %% ../nbs/02_refactor.ipynb #77bc4c3e
def _repoint(path, text, src_mod, dest_mod, names):
    "One file's imports of `names`, pointed at `dest_mod`."
    here, moved = module_of(path), set(names)
    tree, starts = _parse(path, text), _starts(text)
    bound, edits, hit, notes, gained = _bound(tree), [], False, [], set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or _absolute(node, here) != src_mod: continue
        taken = [a for a in node.names if a.name in moved]
        if not taken: continue
        hit = True
        keep = [a for a in node.names if a.name not in moved]
        a, b = _at(text, starts, node)
        indent = text[starts[node.lineno - 1]:a]
        lines = ([_from(node, keep)] if keep else []) + [_stmt(dest_mod, here, [_spec(x) for x in taken])]
        edits.append((a, b, ('\n' + indent).join(lines)))
    prefixes = {(a.asname or a.name): (n, a) for n in ast.walk(tree) if isinstance(n, ast.Import)
                for a in n.names if a.name == src_mod}
    for prefix, (node, alias) in prefixes.items():
        root = prefix.split('.')[0]
        reached = [n for n in ast.walk(tree) if isinstance(n, ast.Attribute) and n.attr in moved
                   and ''.join(text[slice(*_at(text, starts, n))].split()) == f'{prefix}.{n.attr}']
        if not reached: continue
        clash = sorted({n.attr for n in reached} & set(bound))
        if clash:
            notes.append(f'{Path(path).name} already binds {", ".join(clash)}; its `{prefix}.` uses were left alone')
            continue
        hit = True
        for n in reached: edits.append((*_at(text, starts, n), n.attr))
        gained |= {n.attr for n in reached}
        loads = sum(1 for n in ast.walk(tree) if isinstance(n, ast.Name) and n.id == root and isinstance(n.ctx, ast.Load))
        if loads == len(reached):
            if len(node.names) == 1: edits.append((starts[node.lineno - 1], starts[node.end_lineno], ''))
            else: edits.append((*_at(text, starts, node),
                                'import ' + ', '.join(_spec(x) for x in node.names if x is not alias)))
    if gained: edits += _add_imports(text, tree, starts, here, {dest_mod: gained}, set())
    if not hit: return None, notes
    return _apply(text, edits), notes

def _gained(path, before, after):
    "Names `after` reads without binding that `before` did not, which is how a move breaks a file."
    btree, atree = _parse(path, before or ''), _parse(path, after)
    keep = _BUILTINS - set(_bound(btree))   # a definition that shadowed a builtin still has to be found
    return sorted(_free([atree], keep) - _free([btree], keep))

# %% ../nbs/02_refactor.ipynb #5b32a11d
def move_plan(src, names, dest, others=(), shim=True, read=_read):
    """Move `names` from `src` into `dest` and repoint every file in `others` that imported them.

    `read` returns a file's text, or None when it does not exist. A destination that did not exist
    comes back with `before` None, which is what makes undo delete it again."""
    src, dest, names, notes = str(src), str(dest), list(names), []
    if not names: raise ValueError('choose a function or class to move')
    if Path(src).resolve() == Path(dest).resolve(): raise ValueError('choose a different file to move into')
    if Path(dest).suffix != '.py': raise ValueError('a move lands in a Python file')
    source = read(src)
    tree, starts = _parse(src, source), _starts(source)
    src_mod, dest_mod = module_of(src), module_of(dest)
    top = {n.name: n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))}
    missing = [n for n in names if n not in top]
    if missing: raise ValueError(f"{', '.join(missing)} is not a top-level function or class in {Path(src).name}")
    moved = [top[n] for n in names]
    spans = sorted(_span(source, starts, n) for n in moved)
    block = ''.join(source[a:b] for a, b in spans).strip('\n') + '\n'
    rest = _apply(source, [(a, b, '') for a, b in spans])
    if rest.strip(): rest = rest.rstrip('\n') + '\n'   # what a definition leaves behind should not end in blank lines
    bound, froms, plains, back = _bound(tree), {}, set(), []
    for name in sorted(_free(moved) - set(names)):
        node = bound.get(name)
        if node is None: continue
        if isinstance(node, (ast.Import, ast.ImportFrom)): _carry(froms, plains, node, name, src_mod)
        else: back.append(name)
    if back: froms.setdefault(src_mod, set()).update(back)

    dtext = read(dest)
    fresh = dtext is None
    dtext = dtext or ''
    dtree, dstarts = _parse(dest, dtext), _starts(dtext)
    clash = [n for n in names if n in _bound(dtree)]
    if clash: raise ValueError(f"{Path(dest).name} already defines {', '.join(clash)}")
    dedits = _add_imports(dtext, dtree, dstarts, dest_mod, froms, plains)
    if (e := _all_edit(dtext, dstarts, dtree, add=names)): dedits.append(e)
    dbody = _apply(dtext, dedits)
    dafter = (dbody.rstrip('\n') + '\n\n\n' + block) if dbody.strip() else block

    rtree, rstarts = _parse(src, rest), _starts(rest)
    used = sorted(n for n in names if n in _free([rtree], _BUILTINS - set(names)))
    want = names if shim else used
    # A re-export the source does not otherwise need is dropped rather than refused: keeping it
    # would import the two modules into each other for nothing.
    if want and back:
        if used: raise ValueError(f'{src_mod} and {dest_mod} would import each other over '
                                  f'{", ".join(back)}; move those as well')
        want = []
        notes.append(f're-export left out: {dest_mod} imports {", ".join(back)} back from {src_mod}')
    sedits = _add_imports(rest, rtree, rstarts, src_mod, {dest_mod: set(want)}, set()) if want else []
    if (e := _all_edit(rest, rstarts, rtree, drop=() if shim else names)): sedits.append(e)
    safter = _apply(rest, sedits)

    rows = [FileEdit(src, source, safter, len(names)),
            FileEdit(dest, None if fresh else dtext, dafter, len(names))]
    for path in others:
        if Path(path).resolve() in (Path(src).resolve(), Path(dest).resolve()): continue
        text = read(path)
        if text is None: continue
        try: after, said = _repoint(path, text, src_mod, dest_mod, names)
        except ValueError as e: notes.append(str(e)); continue
        notes += said
        if after is not None and after != text: rows.append(FileEdit(str(path), text, after, 1))
    for row in rows:
        if (broke := _gained(row.path, row.before, row.after)):
            raise ValueError(f"{Path(row.path).name} would lose {', '.join(broke)}; move what it needs as well")
    return rows, notes
