"""Registers kosha as a pyskill so LLM hosts can discover and use the Kosha API."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_skill.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/02_skill.ipynb #ac13c6ef
'''kosha — FTS5 + vector search + call graph over your repo and installed packages.

Instantiate with `k = Kosha()` (uses `.kosha/` db in cwd by default).
Then call `doc(Kosha)` for the full API or jump straight to `k.context()`.

Key workflows:
  k.sync()                                         # index repo + env packages + call graph
  k.context("how does X work")                     # fan-out search with graph enrichment
  k.api_call_paths("fasthtml", "starlette")        # shortest call paths between two packages
  k.dep_stack(["myapp"], depth=2)                  # BFS dependency layers ordered by coupling
  k.public_api("fastcore")                         # public API entries for a package
  k.ni("fastcore.basics.merge")                    # node info: callers, callees, pagerank
'''

from .core import Kosha
from pyskills.core import allow

__all__ = ['Kosha']

allow({Kosha: ...})
