"""The `kosha` pyskill: persistent knowledge of your repo and installed packages for coding agents.
`from kosha.skill import *` then `Kosha().context('what you want')` surfaces existing code -- FTS5 + vector
search + call graph merged with RRF -- before you Grep, Read, or search the web.

Docs: https://vedicreader.github.io/kosha/skill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_skill.ipynb.

# %% auto #0
__all__ = ['Kosha', 'pkg_url']

# %% ../nbs/02_skill.ipynb #cell-skill-imports
from .core import Kosha, pkg_url

# %% ../nbs/02_skill.ipynb #cell-skill-all
_all_ = ['Kosha', 'pkg_url']
